src/Command/MakeCommandCommand.php
=> Invocation paramter type are not compatible with declared

src/Resources/doc/index.rst
=> Fixes typo in commands namespace.

src/Validator.php
=> Improving error message style on invalid class name

src/Resources/skeleton/controller/Controller.php.txt, src/Resources/skeleton/controller/ControllerWithTwig.php.txt
> https://symfony.com/doc/master/best_practices/controllers.html#controllers
> [Best Practice] Make your controller extend the `AbstractController` base controller provided by Symfony and use annotations to configure routing, caching and security whenever possible.
> https://symfony.com/doc/master/best_practices/controllers.html#fetching-services
> [Best Practice] Don't use `$this->get()` or `$this->container->get()` to fetch services from the container. Instead, use dependency injection.
=> Extending from AbstractController in controller skeletons

composer.json, src/Command/MakeSerializerEncoderCommand.php, src/Resources/help/MakeSerializerEncoder.txt, src/Resources/skeleton/serializer/Encoder.php.txt, tests/Command/FunctionalTest.php
@javiereguiluz - I know that this is an early stage of this repository and you've mentioned in #27 that the focus should be more on fixing current issues and problems. I would love to help on those :)
Nevertheless I hope you'll find this PR useful as a implementation of one of proposed commands from #17.
=> Added MakeSerializerEncoder command.

src/Maker/MakeFunctionalTest.php
Same as other commands, the generated file does not work if all dependencies are not available.
=> Add BrowserKit component as dependency to functional test commands

src/Resources/doc/index.rst
Referencing #72 for syntax consistency between docs and code.
=> Docs syntax consistency fix.

src/Resources/skeleton/controller/Controller.tpl.php, src/Resources/skeleton/controller/ControllerWithTwig.tpl.php
`Symfony\Bundle\FrameworkBundle\Controller\AbstractController` doesn't implement `getParameter` method. I replaced it by `Symfony\Bundle\FrameworkBundle\Controller\Controller`
- `bin/console make:controller HomeController`
- Open `/home`
=> Fix extends on ControllerWithTwig template

src/Resources/skeleton/authenticator/Empty.tpl.php
Class `Symfony\Component\Security\Guard\GuardAuthenticator;` does not exist.
=> Fix undefined class GuardAuthenticator

src/Resources/doc/index.rst
I suggest to add --dev option to the composer require command in the docs because the maker bundle shouldn't be needed in production environment, in fact flex already registers it automatically to be used only in dev...
=> add --dev option with composer

src/Resources/doc/index.rst
Guys, 
I've decided to share with you my thoughts on maker-bundle docs over this PR instead of raising the new issue to be more clear. 
Current version of `Creating your Own Makers` consists of one stub class than can be used for creating new maker command. I know that the last paragraph explain everything ("For examples of how to complete this class, see the core maker commands") but at this point for me, the user of this bundle, is not really clear even for easy stuff I will have to check core command to see how methods are filled. 
Also I can see the following inconsistencies throughout the class: 
1. `use Symfony\Bundle\MakerBundle\Str;` and `use Symfony\Bundle\MakerBundle\Validator;` are not used within this example
2. `name` feels for me more as class name than format.
3. We are …
=> Docs ammends for example class

src/Exception/RuntimeCommandException.php
@weaverryan Look like throwing a `Symfony\Component\Console\Exception\RuntimeException` into validator function breaks the [loop](https://github.com/symfony/symfony/blob/784186b2498303343a684a6a6f71eca1f7fa2bf2/src/Symfony/Component/Console/Helper/QuestionHelper.php#L364-L365).
But still we need a nice error message without line trace, so implementing `ExceptionInterface` should be enough.
Fix #90.
=> If value fails validation, ask again!

.gitignore, CHANGELOG.md, src/ApplicationAwareMakerInterface.php, src/Command/MakerCommand.php, src/ExtraGenerationMakerInterface.php, src/Maker/AbstractMaker.php, src/Maker/MakeAuthenticator.php, src/Maker/MakeCommand.php, src/Maker/MakeController.php, src/Maker/MakeEntity.php, src/Maker/MakeForm.php, src/Maker/MakeFunctionalTest.php, src/Maker/MakeMigration.php, src/Maker/MakeSerializerEncoder.php, src/Maker/MakeSubscriber.php, src/Maker/MakeTwigExtension.php, src/Maker/MakeUnitTest.php, src/Maker/MakeValidator.php, src/Maker/MakeVoter.php, src/MakerInterface.php, src/Resources/config/makers.xml, src/Resources/doc/index.rst, src/Resources/help/MakeMigration.txt, src/Resources/skeleton/test/Functional.tpl.php, src/Test/MakerTestCase.php, src/Test/MakerTestDetails.php, tests/Maker/FunctionalTest.php, tests/fixtures/MakeFunctional/config/routes.yaml, tests/fixtures/MakeFunctional/src/Controller/MainController.php, tests/fixtures/MakeMigration/src/Entity/SpicyFood.php
This replaces #10.
There are 2 cases:
(A) When there ARE schema changes:
(B) When there are NOT schema changes:
This includes a BC break on `MakerInterface`, but it will only affect people who have created custom makers (and they'll get a clear error).
=> New make:migration command

src/Resources/doc/index.rst
The link AbstractMaker goes to the current page and is not going to AbstractMaker Class on Github.
I think it should be like that.
=> AbstractMaker link

composer.json
According to `composer validate` the property description is required.
I did also add the property homepage in an separate commit. So you can cherry pick if you want.
=> Add description and homepage to composer.json

src/Command/MakerCommand.php
This bundle doesn't use flex or require flex to work. It just makes assumptions about the directory structure based on the latest recommendations for Symfony.
This bundle can also be useful for projects that don't use flex yet ;-)
=> Remove check if symfony/flex is installed

src/DependencyBuilder.php, src/Maker/MakeController.php, src/Test/MakerTestDetails.php
Also needed tweak to a test so that this dep IS installed in the functional tests, even though the class exists in MakerBundle itself.
The cool thing is that the test failure *was* correct: we mis-configured the dependencies on this maker (the user DOES have the `Route` class, but even still, they need to install a library so it's loaded).
=> Fixing dependency issue on maker

src/Resources/skeleton/doctrine/Repository.tpl.php
It helps IDE to get correct type if you do calls like this
```php
$user = $this->userRepository->find(1);
$user->getId(); //IDE knows that this is a User class and gives correct autocomplete
```
=> Type hints for repositories

.travis.yml
Usually this is done by fabbot, but it mis-reports all of our `[]` as invalid. I'd rather not use fabbot (it makes all of our PR's look like build failures) and just validate the CS on the tests.
=> Running phpcs on Travis

composer.json, src/Test/MakerTestCase.php
A simple way to help make sure we generate decent code - it will help #113, which has a few violations ;).
=> Using a Twig CS tool to verify our generated Twig code

.appveyor/composer.bat, appveyor.yml, src/FileManager.php, src/Test/MakerTestCase.php, tests/DependencyBuilderTest.php, tests/FileManagerTest.php, tests/Maker/FunctionalTest.php
See #124 - let's get tests running on Windows :)
=> Initial attempt for appveyor support & Windows path fix

src/Resources/skeleton/crud/controller/Controller.tpl.php, tests/Maker/FunctionalTest.php, tests/fixtures/MakeCrudRepository/src/Entity/SweetFood.php, tests/fixtures/MakeCrudRepository/src/Repository/SweetFoodRepository.php, tests/fixtures/MakeCrudRepository/tests/GeneratedCrudControllerTest.php
Lets start from `Controller::delete` action. I don't think we need 2 return statements here.
Maybe it will be better to add some flash messages?
=> make:crud skeleton optimization

phpunit.xml.dist, src/Validator.php, tests/ValidatorTest.php
error when run `doctrine:schema:update --dump-sql` after creating entity using maker-bundle because of the attribute type error.
for example when generate field with length 100 the annotation will be generate like this
`@ORM\Column(type="string", length="100", nullable=true)` and when run the schema update command will throw exception 
```
In AnnotationException.php line 83:
[Type Error] Attribute "length" of @ORM\Column declared on property App\Entity\Entity::$field expects a(n) integer, but got string.
```
and it is also affect for `precision` and `scale`
=> Fix expected variable type

.gitattributes
This is different than the policy in symfony/symfony. But, this library is a bit different:  the tests do *not* contain example usage code, as most of the classes are internal. By not packing the tests/ directory, we avoid polluting the user's project with extra User classes (etc) that confuse IDE's.
Fixes #144
=> Ignorning tests so it is not downloaded via Composer

src/Str.php, tests/StrTest.php
=> make entity, related class without namespace

src/Doctrine/EntityDetails.php
=> fix ClassMetadata namespace

src/Maker/MakeEntity.php
Scale value currently overwrites the previously entered precision value.
=> Decimal Type: Fix small typo

src/Resources/config/services.xml, src/Util/AutoloaderUtil.php, tests/Util/AutoloaderUtilTest.php
If the default folder for vendor is changed the AutloaderUtil class is no more able to find the ClassLoader. Testing the failure can be easily done by changing the **vendor-dir** in composer.json. After adjusting the autoload require in console file, all makers that use AutoloadUtil will fail.
Motivation behind this is development with docker. The application is a lot faster on windows and mac if the vendor folder is not a shared folder.
=> Get the autoloader class from current registered autoload functions

src/Generator.php
=> Better message with full namespace

.php_cs.dist, src/Doctrine/EntityRegenerator.php
On Mac, an instance of `Doctrine\Common\Persistence\Mapping\MappingException` is thrown by Doctrine when a mapping file references a non-existing class. Currently, the code only catches `Doctrine\ORM\Mapping\MappingException` instances.
This PR makes the tests green on Mac (https://github.com/symfony/maker-bundle/issues/167#issuecomment-387976395). This also probably fixes a real bug.
I've no idea why Doctrine throws a different exception on Mac than on Linux.
=> Fix the EntityRegenerator on Mac

src/Command/MakerCommand.php, src/DependencyBuilder.php, src/Doctrine/DoctrineHelper.php, src/Doctrine/EntityRegenerator.php, src/Doctrine/EntityRelation.php, src/EventRegistry.php, src/FileManager.php, src/Maker/MakeEntity.php, src/Maker/MakeValidator.php, src/Str.php, src/Test/MakerTestCase.php, src/Test/MakerTestEnvironment.php, src/Test/MakerTestProcess.php, src/Util/AutoloaderUtil.php, src/Util/ClassSourceManipulator.php, src/Validator.php
Fix some quality issues and add some minor performance improvements (analysis done with [PHP Inspections](https://github.com/kalessil/phpinspectionsea)).
=> Quality fixes (PHP Inspections)

src/Doctrine/EntityRegenerator.php, src/Util/ClassSourceManipulator.php, tests/Doctrine/EntityRegeneratorTest.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/BaseClient.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Embed.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/BaseClient.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/Embed.php, tests/Doctrine/fixtures/source_project/src/Entity/BaseClient.php, tests/Doctrine/fixtures/source_project/src/Entity/Client.php, tests/Doctrine/fixtures/source_project/src/Entity/Embed.php, tests/Doctrine/fixtures/source_project/src/Entity/TeamTrait.php, tests/Doctrine/fixtures/source_project/src/Entity/TimestampableTrait.php
Should fix #167 
**What has been fixed**
- generation for mapped inherited fields
- generation for mapped fields that come from direct traits
- skipping ```parent::__construct()``` if Entity has parent class and it has constructor
**How it is done**
- fields (fields, and associations, but not embedded) are checked before generation, generation happens only for class' fields
- ClassSourceManipulator is updated to include parent call (if parent class exists and the class has already been generated)
- EntityRegeneratorTest skips copying of Traits as it causes autoloader to fail (again, strangely, on Travis only, works fine on Mac)
Verified on live project, seems to generate OK with a lot of different entities (MappedSuperclasses, DiscriminatorMaps etc).
=> fixed EntityRegenerator when using MappedSuperclass or Traits

src/Util/ClassNameDetails.php
=> Fix: Case mismatch

.travis.yml, composer.json
This PR
💁‍♂️ It's already configured in [`composer.json`](https://github.com/symfony/maker-bundle/blob/bb0485a3b2eecc561eff735109316677e18fb1d1/composer.json#L35-L37).
=> Fix: No need to specify preferred installation method on Travis

src/Resources/skeleton/twig/Extension.tpl.php
This fixes #200.
I disagree with this change ... but I guess most people will agree with it ... so let's do it.
=> Don't make Twig filters safe for HTML by default

src/Resources/skeleton/test/Functional.tpl.php
`:contains` is a proprietary jQuery selector, and has been explicitly removed from the CSS 3 spec: https://stackoverflow.com/questions/4781141/why-doesnt-the-selector-h3nth-child1containsa-work/4781167#4781167
Then, it doesn't work with Panthère (it's actually supported by Selenium, but not by WebDriver).
I propose to use Xpath instead.
=> Don't use :contains in the functional test tpl

src/Util/ClassSourceManipulator.php, src/Util/PrettyPrinter.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/source/ProductWithTabs.php, tests/Util/fixtures/with_tabs/ProductWithTabs.php
Woo! Fixes #170 
PHP-Parser is responsible for determining indentation for new code. When tabs are used, it sees this as 1 indent, and uses 1 space to indent. This had two side-effects:
1) My original `str_replace` code was not smart enough to handle that. Easy fix using regex
2) In general, any new code (e.g. getter method) is indented with 1 space.
=> Fixing bad empty line when source file uses tabs

src/Maker/MakeEntity.php
fixes #192 
When we're trying to generate an entity inside a folder, and when the namespace of the newly created correspond to an entity that already exists, an error occurs : 
> In MakeEntity.php line 840:
> Call to a member function getName() on string
Ex :
An entity called App\Entity\BlogPost exists, and we try to create an entity named "BlogPost\Comment" 
Actually `Str::getNamespace($className)` refers to an existing class and not to a namespace, then $doctrineHelper->getMetadata() won't return an array, but a single metadata, and this leads to an error.
To prevent this behavior, the easier way is to put a trailing backslash at the end of the namespace name, so we know it won't refer to a classname.
=> fix MakerEntity when generating entity inside folder

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php
This PR would close #240 and update the `make:crud` command to correctly use Symfony's Routing component instead of the deprecated `FrameworkExtraBundle`'s. Would appreciate a thorough review as all I did was basically look at @javiereguiluz's PR #221 for the AbstractController fix.
=> Extend from AbstractController and use Symfony's @Route

src/Maker/MakeCrud.php
The make:crud controllers rely on ParamConverters,
which are provided by framework-extra-bundle.
Fixes #255
=> Add framework-extra-bundle dependency

src/Util/YamlSourceManipulator.php, tests/Util/yaml_fixtures/add_array_to_null.test, tests/Util/yaml_fixtures/add_key_to_null.test, tests/Util/yaml_fixtures/add_new_item_in_multiline_hash.test
Fixing 2 separate bugs in `YamlSourceManipulator` reported by @nikophil. These likely aren't affecting the library now, but we'll use these situations soon in some new features :).
Cheers!
=> Fix 2 YamlSourceManipulator bugs

phpunit.xml.dist, src/Test/MakerTestEnvironment.php
This is a repeat of #237. The tests have been failing for too long. I think we need to fix them, and then we can revert later when doctrine/orm v2.6.3 is released.
Cheers!
=> Working around deprecation errors to get the test suite to pass

src/Maker/MakeAuthenticator.php, src/Resources/config/makers.xml, src/Security/InteractiveSecurityHelper.php, src/Security/SecurityConfigUpdater.php, src/Util/YamlSourceManipulator.php, tests/Maker/FunctionalTest.php, tests/Security/InteractiveSecurityHelperTest.php, tests/Security/SecurityConfigUpdaterTest.php, tests/Security/yaml_fixtures/expected_authenticator/empty_source.yaml, tests/Security/yaml_fixtures/expected_authenticator/simple_security_source.yaml, tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls.yaml, tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls_and_authenticator.yaml, tests/Security/yaml_fixtures/source/simple_security_with_firewalls.yaml, tests/Security/yaml_fixtures/source/simple_security_with_firewalls_and_authenticator.yaml, tests/fixtures/MakeAuthenticator/config/packages/security.yaml, tests/fixtures/MakeAuthenticatorExistingAuthenticator/config/packages/security.yaml, tests/fixtures/MakeAuthenticatorExistingAuthenticator/src/Security/Authenticator.php, tests/fixtures/MakeAuthenticatorMultipleFirewalls/config/packages/security.yaml, tests/fixtures/MakeAuthenticatorMultipleFirewallsExistingAuthenticator/config/packages/security.yaml, tests/fixtures/MakeAuthenticatorMultipleFirewallsExistingAuthenticator/src/Security/Authenticator.php
This PR adds the newly created authenticator to `security.yaml`
The process is the following :
- if no firewall exist, a "main" firewall is automatically created (this should never happen)
- if there is only one "real" firewall (i.e. : a firewall withou security: false"), the authenticator is added to this firewall
- if there are more than one firewall, the user is asked to which firewall the authenticator should be added
- if the target firewall already has an authenticator, the user is asked which authenticator should be the entry point.
=> MakeAuthenticator : update security.yaml

src/Command/MakerCommand.php
Not having the link end in a period makes it easier to click or copy/paste. This is also consistent with a few other places in the same bundle.
=> Tiny fix: Don't end the link with a 'period'.

src/Resources/skeleton/security/Voter.tpl.php
This is a bit longer, but this is much more explicite.
This is much easier to find all usage in a code base because the term is now unique
=> [Voter] use ENTITY_ATTR instead of ATTR

src/Maker/MakeAuthenticator.php, src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php, src/Str.php
The idea is that this is easier and more self-documenting than teaching the user to translate the "Username could not be found." message.
```diff
// src/Security/LoginFormAuthenticator.php
// ...
public function getUser($credentials, UserProviderInterface $userProvider)
{
// ...
-   return $this->entityManager->getRepository(User::class)->findOneBy([
+   $user = $this->entityManager->getRepository(User::class)->findOneBy([
'email' => $credentials['email'],
]);
+   if (!$user) {
+       // fail authentication with a custom error
+       throw new CustomUserMessageAuthenticationException('Email could not be found.');
+   }
+   return $user;
}
```
Cheers!
=> Throwing CustomUserMessageAuthenticationException in make:auth login

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php
There is a mistake in crud controller template :
Example  (`src/Resources/skeleton/crud/controller/Controller.tpl.php` - line 35) : 
`return $this->render('<?= $route_name ?>/index.html.twig', ['<?= $entity_twig_var_plural ?>' => $<?= $entity_var_plural ?>]);`
With an entity with following path :` Entity/Foo/BarBar.php` , `$route_name` will be equal to `foo_bar_bar` and does not correspond with the `index.html.twig` path (should be `foo/bar_bar`).
This pull request fix this by adding the `$templatesPath` var, used to create twig templates, for the controller generation.
:)
=> Fix crud controller template

src/Maker/MakeUser.php
We fully need SecurityBundle so the recipe has been executed.
Discovered at a workshop - if you installed `security-csrf` first, and then ran this command, it would allow you to continue, though the `security.yaml` file would be missing.
=> Fix make:user dependency: more precise to get the recipe

src/Resources/skeleton/security/Voter.tpl.php
People could replace only the `BlogPost` class. So the support method will always return `false`.
With a leading `\`, the class name will resolve "normally"
=> [Voter] Use the subject's FQCN in the support method

src/Resources/skeleton/crud/controller/Controller.tpl.php, tests/fixtures/MakeCrud/tests/GeneratedCrudControllerTest.php, tests/fixtures/MakeCrudInCustomRootNamespace/tests/GeneratedCrudControllerTest.php
Update the generated edit action.
This now redirects to the index instead of the edit form.
Fixes #257
=> [CRUD] Redirect to index after edit

tests/Maker/FunctionalTest.php
Problem: Tests are failing due to the name of the fixture which is *AppFixture*. But a fixture with that name is created by [DoctrineFixtures recipe](https://github.com/symfony/recipes/commit/c447845d62ffa63eb940db89ed00a92b00350fe5).
As talked during #SymfonyConHackDay2018, the fix was to change the name of the fixture's that we want to create during the tests.
=> Fix name of fixture in tests

.travis.yml, src/GeneratorTwigHelper.php, src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php
Added datetimetz, *_immutable, dateinterval and json fileds processing.
closes #234
closes #270
=> make:crud | Improvements

src/Maker/MakeController.php, src/Resources/help/MakeController.txt, src/Resources/skeleton/controller/Controller.tpl.php, tests/Maker/FunctionalTest.php
I had several times the case in which I did not necessarily need a template when I generated a controller. So I'm trying to add an option `--no-template` to force avoid template generation.
I think that I will need help on tests writing ;)
=> Add --no-template option for make:controller command

src/Str.php, src/Validator.php, tests/ValidatorTest.php
Validator should also check if the given class name is a reserved keyword or not.
However we have to come up with a better exception message, since this one does not reflect the error. Any suggestion?
Thanks for your help @weaverryan during #SymfonyConHackDay2018
Fixes #305
=> Checking on reserved keywords for class name validity.

src/Resources/skeleton/crud/controller/Controller.tpl.php
As stated by @kunicmarco20 [here](https://github.com/symfony/symfony-docs/pull/10588#pullrequestreview-172694490), no abbreviations should be used in var names.
This PR fixes this in the generated Controller for `make:crud`
=> [CRUD] Remove abbreviation in var name $em

src/Resources/doc/index.rst
We have been confused because the documentations states that Symfony Flex is required in order to use the MakerBundle.
However, we are not using Symfony Flex in our application yet, but it was still possible to use the MakerBundle. So I would suggest to remove the part saying that Symfony Flex is a dependency.
=> Remove Symfony Flex dependency from MakerBundle

src/Maker/MakeRegistrationForm.php
https://symfony.com/doc/current/doctrine/registration_form.html#registration-password-max
=> Adding a max length validator

src/Doctrine/DoctrineHelper.php, src/Maker/MakeEntity.php, tests/fixtures/MakeEntityXmlMappingError/config/doctrine/User.orm.xml
Closes #299 according to https://github.com/symfony/maker-bundle/pull/185#issuecomment-389009674
Also alternative for https://github.com/symfony/maker-bundle/pull/185, https://github.com/symfony/maker-bundle/pull/265 and https://github.com/symfony/maker-bundle/pull/310
=> Fix Entity directory does not exist

src/Security/InteractiveSecurityHelper.php
Better message when try to generate authenticator through `make:auth` command.
Before:
After:
=> Exception when property not found in given user entity

src/Validator.php
After using ``make:entity Self`` or ``make:entity Parent``, maker-bundle build 2 files :
```
created: src/Entity/Self.php
created: src/Repository/SelfRepository.php
```
But, after that :
```
Fatal error: Cannot use 'Self' as class name as it is reserved in /var/www/html/demo/src/Entity/Self.php on line 10
```
... and others "Call Stack" to finish with a "CRITICAL".
You must remove ``src/Entity/Self.php`` and ``src/Repository/SelfRepository.php`` to continue.
=> make:entity "Self" or "Parent"

src/Resources/doc/index.rst
By default, the maker bundle is only active in `dev` environment, so the configuration file should be in the `config/packages/dev/` directory, not directly in the `config/packages/`
=> MakerBundle doc : use dev file name

src/Maker/MakeEntity.php, tests/Maker/FunctionalTest.php, tests/fixtures/MakeEntityExistsInRoot/src/Entity/Directory.php, tests/fixtures/MakeEntityExistsInRoot/tests/GeneratedEntityTest.php
As in #322 the entity maker cannot make a relation, where the target entity is also presented in the root namespace, beacuse `Symfony\Bundle\MakerBundle\Maker\MakeEntity::askRelationDetails()` looks for it in the root namespace at first.
I don't think this is the good behaviour.
This PR makes it look for first in the namepace defined in the config, and after that in other places.
=> Look for the target entity in the namespace first

src/Maker/MakeFunctionalTest.php, src/Resources/skeleton/test/Functional.tpl.php
Hi, this PR is to fix the way of calling the assertions static methods of PHPunit in the generated unit and functional tests.
[First commit](https://github.com/symfony/maker-bundle/commit/8f4af140015f6e30fe871fbacbc8c066901e0a25) : As pointed out in [this article](https://arkadiuszkondas.com/the-right-way-to-call-assertion-in-phpunit/), we should not be calling the assertions using `$this->assert*` but instead with `static::assert*`.
[Second commit](https://github.com/symfony/maker-bundle/commit/cfb0715dc99fb6cac45f08a6c3daefc3bafba542) : To go further, we can use [the new assertion API](https://github.com/symfony/symfony/pull/30813) provided by the `WebTestCase`.
I don't kown if this could be considered a BC break... but i hope not.
=> [make:*-test] Use the new WebTestAssertionsTrait methods in the generated functional tests

src/Validator.php, tests/ValidatorTest.php
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed tickets    | #249
| Deprecations? | no
| License       | MIT
This checks if the input string is a UTF-8-encoded, and throws an exception if not.
=> [Validator] Add encoding test to validateClassName

src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/twig_template.tpl.php, tests/fixtures/MakeRegistrationFormEntity/tests/RegistrationFormTest.php
Add a agree terms checkbox.
Should fix https://github.com/symfony/maker-bundle/issues/340
=> Add a agree terms checkbox

tests/ValidatorTest.php
I don't know why this test was written like that, and I did not find other way to fix it...  
Hope I'm not missing something.
=> Fix the 'Invalid encoding' class name validation test.

composer.json
Hello,
Since https://github.com/friendsoftwig/twigcs/pull/68, the tool moved from `allocine` to `friendsoftwig` and will receive new updates (bugfixes, new twig syntax support, ...) from here.
Here's a PR to handle this change !
=> Switch to the new twigcs library

src/DependencyInjection/MakerExtension.php, src/Resources/config/services.xml, src/Util/ComposerAutoloaderFinder.php, tests/Maker/FunctionalTest.php, tests/Util/AutoloaderUtilTest.php, tests/Util/ComposerAutoloaderFinderTest.php
When the project, or dependent package, adds a custom autoloader, e.g. PhpStan, the added autoloader will be returned instead of the one containing the project's autoloader when `ComposerAutoloaderFinder` iterates the autoloader list leading to the mysterious error:
```
Could not determine where to locate the new class "App\Controller\DeliciousPuppyController", maybe try with a full namespace like "\My\Full\Namespace\DeliciousPuppyController"
```
Fixes #196
Fixes #231
Fixes #313
Related #378
=> More robust autoloader detection

src/Maker/MakeEntity.php
When creating a new relation, if the requested class is not found, the error message should refer to the answered class, not to the $targetEntityClass variable, as it is now, because this variable is always null at this point in the code, as per while condition, and it always prints an empty string in the message for the class.
=> Fixed error message when class is unknown on creating relation

src/Resources/skeleton/authenticator/login_form.tpl.php
A little fix when generate guard auth in login form skeleton. "checkbox" class is also useless.
=> Fix unclosed div on login form skeleton

src/DependencyBuilder.php, tests/DependencyBuilderTest.php
This is related to [this comment](https://github.com/symfony/maker-bundle/pull/417#discussion_r293936255) by @weaverryan  
Let me know if this is not the way to go, or if the PR is missing something.
=> Use trait_exists when trying to figure out if a dependency is missing or not.

src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/implements_interface/User_simple_with_interface.php, tests/Util/fixtures/source/User_simple_with_interface.php
The bug where this workaround was needed for was fixed, so let's remove this workaround. This will make sure adding an interface to a class with another interface will also work now.
See: https://github.com/nikic/PHP-Parser/pull/527
=> Remove php-parser workaround for adding interfaces

src/Maker/MakeController.php, src/Maker/MakeRegistrationForm.php
=> Require doctrine/annotations instead of sensio/framework-extra-bundle where sufficient

.travis.yml, src/Test/MakerTestEnvironment.php, src/Util/ComposerAutoloaderFinder.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php, tests/fixtures/MakeCrudRepository/src/Repository/SweetFoodRepository.php
Trying to strike a balance between having a very robust test suite, and one that takes too long to execute & blocks jobs under the `symfony/` organization.
=> Minimizing test matrix + fixing tests

src/Security/InteractiveSecurityHelper.php, tests/Maker/FunctionalTest.php, tests/Security/InteractiveSecurityHelperTest.php
Hello,
It is possible in vanilla Symfony to change how the User is retrieved by the `entity` user provider, so you use your own repository - [https://symfony.com/doc/current/security/user_provider.html#using-a-custom-query-to-load-the-user](https://symfony.com/doc/current/security/user_provider.html#using-a-custom-query-to-load-the-user). Then you remove `providers.xxxx.entity.property` key.
Unfortunately, it causes `make:auth` command to crash:
This PR patches `InteractiveSecurityHelper`, so it checks `property` key exists before reading from it. No BC break.
I added a test for that very specific use case.
=> Fixed make:auth when using a custom repository method as UserProvider

src/Resources/skeleton/authenticator/login_form.tpl.php
Although common, placing the label into the placeholder is bad practice and reduces usability and accessibility. If people wanna do it this way, they still can; but it shouldn't be suggested :-)
If you merge it, I'll update the docs at https://symfony.com/doc/current/security/form_login_setup.html#generating-the-login-form too.
=> Changed placeholder to real label

src/Maker/MakeFunctionalTest.php
This fixes #483.
We'll re-add Panther dependency when/if we create a maker for e2e tests.
=> Removed Panther dependency from the functional test maker

src/Maker/MakeFunctionalTest.php
As of Symfony 5, the Client class has been renamed and does not exist anymore.
=> Fix make:functional-test for Symfony 5

.travis.yml, src/Test/MakerTestDetails.php, src/Test/MakerTestEnvironment.php
Improve symlinking phpunit-bridge inside testing flex project.
=> [sfhackday2019] Fixing tests

.travis.yml, src/EventRegistry.php, src/Test/MakerTestEnvironment.php, src/Util/YamlSourceManipulator.php, tests/EventRegistryTest.php, tests/Maker/FunctionalTest.php, tests/fixtures/MakeRegistrationFormEntity/tests/RegistrationFormTest.php, tests/fixtures/MakeUserEntityPassword/tests/GeneratedEntityTest.php
This also removes the dev-stable. That was a build to detect possible BC breaks on patch versions made in Symfony... which is rare and probably not the job of Maker :).
=> Fixing tests for Symfony5

src/Maker/MakeForgottenPassword.php, src/Renderer/FormTypeRenderer.php, src/Resources/config/makers.xml, src/Resources/help/MakeForgottenPassword.txt, src/Resources/skeleton/forgottenPassword/ForgottenPasswordController.tpl.php, src/Resources/skeleton/forgottenPassword/PasswordResetToken.tpl.php, src/Resources/skeleton/forgottenPassword/PasswordResetTokenRepository.tpl.php, src/Resources/skeleton/forgottenPassword/twig_check_email.tpl.php, src/Resources/skeleton/forgottenPassword/twig_email.tpl.php, src/Resources/skeleton/forgottenPassword/twig_request.tpl.php, src/Resources/skeleton/forgottenPassword/twig_reset.tpl.php, src/Security/InteractiveSecurityHelper.php, tests/Maker/FunctionalTest.php, tests/Security/InteractiveSecurityHelperTest.php, tests/fixtures/MakeForgottenPassword/config/packages/security.yml, tests/fixtures/MakeForgottenPassword/config/packages/swiftmailer.yaml, tests/fixtures/MakeForgottenPassword/config/routes.yaml, tests/fixtures/MakeForgottenPassword/src/Entity/User.php, tests/fixtures/MakeForgottenPassword/tests/ForgottenPasswordControllerTest.php
Hello,
Having a password reset feature ("forgotten password") is a common feature of a web application. Maker bundle already has a User registration maker, it makes sense imo to add this too. Otherwise users are left either to code it manually (long), or to ditch Maker commands for FOSUserBundle.
I started implementing such a maker. It is heavily inspired from other Registration maker regarding style, and from FOSUserBundle process. Right now this is a work in progress, but I wanted to propose the idea & to discuss code style.
To do:
Points to be discussed:
- is the controller right now looking good? I'm trying to have something minimalistic doing the job right, and easily modifiable. Not having too many services/helpers.
- ~~should the e-mail body be from a template, or does an heredoc …
=> Added a "Forgotten password" maker

src/Maker/MakeForgottenPassword.php, src/Renderer/FormTypeRenderer.php, src/Resources/config/makers.xml, src/Resources/skeleton/forgottenPassword/ForgottenPasswordController.tpl.php, src/Security/SecurityControllerBuilder.php, tests/Maker/FunctionalTest.php, tests/Maker/MakeForgottenPasswordTest.php, tests/Security/fixtures/expected/SecurityController_login_logout.php
=> temp. disable make forgotten password

src/Maker/MakeForgottenPassword.php, src/Renderer/FormTypeRenderer.php, src/Resources/skeleton/forgottenPassword/ForgottenPasswordController.tpl.php, src/Security/SecurityControllerBuilder.php, tests/Maker/MakeForgottenPasswordTest.php, tests/Security/fixtures/expected/SecurityController_login_logout.php, tests/Security/fixtures/expected/SecurityController_logout.php
#474 changed implemented \LogicException instead of \Exception for make:auth. Fixture still produced \Exception for assertion.
=> fix security logout fixture

src/Security/SecurityConfigUpdater.php, tests/Security/SecurityConfigUpdaterTest.php, tests/Security/yaml_fixtures/expected_user_class/simple_security_with_single_memory_provider_configured.yaml, tests/Security/yaml_fixtures/source/simple_security_with_single_memory_provider_configured.yaml
this fixes the bug which occurs presently on master
since we remove memory provider in "make:user" if it is the only
provider, we need to remove this memory provider from firewalls.
And the tests were failing now because the security bundle's recipe has been updated recently, and the memory provider has been added to main firewall
=> Fix SecurityConfigUpdater

src/EventRegistry.php
With an addtionnal bundle or a component like "security-bundle", we have an exception
```
Notice: Undefined index: debug.security.authorization.vote
```
Now the mapping is good :
=> make:subscriber: fix list active event

src/EventRegistry.php, tests/EventRegistryTest.php
This caused an undefined index when running `make:subscriber` and choosing a fully-qualified event class as your event string. In this case, `EventRegistry::getEventClassName()` really has no work to do.
=> Fixing bug where passing the full class name as the event didn't return same string

src/Doctrine/DoctrineHelper.php, src/Doctrine/EntityDetails.php
Hi,
just fixing a deprecation from doctrine`Doctrine\Common\Persistence` to `Doctrine\Persistence`
=> Fixing deprecation

src/Maker/MakeEntity.php
I've always found annoying and frustrating that running `make:entity` the output is 
>  Next: When you're ready, create a migration with `make:migration `
instead of 
>  Next: When you're ready, create a migration with `php bin/console make:migration `
As ` make:migration` does
>  Then: Run the migration with `php bin/console doctrine:migrations:migrate`
=> Update success message in MakeMigration

src/Test/MakerTestKernel.php, tests/Doctrine/EntityRegeneratorTest.php
fixes `Since symfony/framework-bundle 5.1: Not setting the "framework.router.utf8" configuration option is deprecated, it will default to "true" in version 6.0.` deprecation warning in tests / ci
not intended to address any other deprecation's or fix/refactor other logic
=> explicitly set framework.router.utf8 value in test kernel

src/Maker/MakeMessage.php, src/Resources/config/makers.xml, src/Resources/help/MakeMessage.txt, src/Resources/skeleton/message/Message.tpl.php, src/Resources/skeleton/message/MessageHandler.tpl.php, tests/Maker/MakeMessageTest.php, tests/fixtures/MakeMessageBasic/config/services_test.yaml, tests/fixtures/MakeMessageBasic/tests/GeneratedMessageHandlerTest.php, tests/fixtures/MakeMessageWithTransport/config/packages/messenger.yaml, tests/fixtures/MakeMessageWithTransport/config/services_test.yaml, tests/fixtures/MakeMessageWithTransport/tests/GeneratedMessageHandlerTest.php
An easy one - generated for Messenger - generates an empty message class and corresponding handler:
**Generated Code**
<details><summary>SendWelcomeEmailMessage</summary>
<p>
```php
<?php
namespace App\Message;
class SendWelcomeEmailMessage
{
/*
* Add whatever properties & methods you need to hold the
* data for this message class.
*
* Note - if you're handling this message async, you may need
* a getter & setter method for each property so that it serializes
* and unserializes correctly.
*/
//     private $name;
//
//     public function __construct(string $name)
//     {
//         $this->name = $name;
//     }
//
//    public function getName(): string
//    {
//        return $this->name;
//    }
//
//    public function setName(string $name)
//    {
//        $this->name = $name;
// …
```
=> New command - make:message for Messenger

phpunit.xml.dist
For example, there is nothing we can do about doctrine/orm using doctrine/common persistence classes. Reference: https://symfony.com/doc/current/components/phpunit_bridge.html#internal-deprecations
=> ignoring external deprecations

src/Generator.php
- file & template generator $variables param is now optional
Not all file and templates require variables to be passed for creation.
=> "Variables" param in file and template generators should be optional

src/Doctrine/EntityClassGenerator.php, src/Doctrine/EntityRegenerator.php, src/Maker/MakeFixtures.php, src/Resources/skeleton/doctrine/Fixtures.tpl.php, src/Resources/skeleton/doctrine/Repository.tpl.php, src/Util/YamlSourceManipulator.php, tests/Doctrine/EntityRegeneratorTest.php, tests/Maker/MakeMessageTest.php
Fixes #570 #560, #524, #528, #519 #570
=> Fixing deprecated Doctrine\Common code in templates

src/Doctrine/DoctrineHelper.php
I think this slipped with PR #545 unintentionally... Causing tests to fail
=> remove unused Doctrine/ORM/Configuration use statement in DoctrineHelper

src/Maker/MakeResetPassword.php, src/Resources/config/makers.xml, src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordRequest.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordRequestFormType.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordRequestRepository.tpl.php, src/Resources/skeleton/resetPassword/twig_check_email.tpl.php, src/Resources/skeleton/resetPassword/twig_email.tpl.php, src/Resources/skeleton/resetPassword/twig_request.tpl.php, src/Resources/skeleton/resetPassword/twig_reset.tpl.php, src/Validator.php, tests/Maker/MakeResetPasswordTest.php, tests/ValidatorTest.php, tests/fixtures/MakeResetPassword/config/packages/security.yml, tests/fixtures/MakeResetPassword/src/Entity/User.php, tests/fixtures/MakeResetPasswordCustomConfig/config/packages/custom_reset_password.yaml, tests/fixtures/MakeResetPasswordCustomConfig/config/packages/security.yml, tests/fixtures/MakeResetPasswordCustomConfig/src/Entity/User.php, tests/fixtures/MakeResetPasswordFunctionalTest/config/packages/mailer.yaml, tests/fixtures/MakeResetPasswordFunctionalTest/config/packages/security.yml, tests/fixtures/MakeResetPasswordFunctionalTest/src/Entity/User.php, tests/fixtures/MakeResetPasswordFunctionalTest/tests/ResetPasswordFunctionalTest.php, tests/fixtures/MakeResetPasswordModifiedConfig/config/packages/security.yml, tests/fixtures/MakeResetPasswordModifiedConfig/src/Entity/User.php
Adds a `make:reset-password` maker to create the classes, entities, and twig templates required by Symfony Casts Reset Password Bundle. This complements the bundle by doing the leg work to provide a true out-of-the-box solution for handling forgotten passwords in traditional Symfony applications.
=> create maker for symfony casts reset password bundle

src/Maker/MakeResetPassword.php, src/Resources/help/MakeResetPassword.txt
Provides helpful information when calling `make:reset-password --help`
=> Add help doc for reset-password

src/Maker/MakeResetPassword.php
To use the classes generated by `make:reset-password` as is, doctrine is required.
=> fixed missing doctrine dependency

src/DependencyInjection/CompilerPass/SetDoctrineManagerRegistryClassPass.php, src/Doctrine/EntityClassGenerator.php, src/Doctrine/EntityRegenerator.php, src/Maker/MakeEntity.php, src/Maker/MakeUser.php, src/MakerBundle.php, src/Resources/config/makers.xml, src/Resources/config/services.xml, tests/Doctrine/EntityRegeneratorTest.php
This problem occurs if using DoctrineBundle 1.11 or lower, where the newer Persistence
alias is not available. This also centralizes the creation of the repository classes
to fix this in all places.
Problem introduced in #570
=> Fixing a bug where the wrong ManagerRegistry was sometimes used in repositories

src/Maker/MakeMigration.php
The command otherwise seems to work just fine on 3.0 alpha.
This should be BC for older versions as the bundle class has always existed.
=> DoctrineCommand is gone in DoctrineMigrationsBundle 3.0

appveyor.yml
A cheap fix to keep AppVeyor on Composer v1
=> Forcing Composer v1

src/DependencyInjection/CompilerPass/RemoveMissingParametersPass.php, src/FileManager.php, src/Resources/config/services.xml, src/Test/MakerTestEnvironment.php, src/Util/MakerFileLinkFormatter.php, tests/Doctrine/EntityRegeneratorTest.php, tests/FileManagerTest.php, tests/Util/MakerFileLinkFormatterTest.php, tests/fixtures/MakeController/config/packages/framework.yaml
This PR aims to display terminal links on the created file paths when the `framework.ide` configuration param (or `debug.file_link_format` container parameter) is set (only displayed if the terminal support it).
=> Allow to display links on created files

src/Renderer/FormTypeRenderer.php
A small change to make use statement unique.
I created a custom maker that add extra informations in EntityFormType, and I find that it's generate a FormType with multiple use statements. (based on MakerCrud).
Before:
```php
<?php
namespace App\Form;
use App\Entity\MyEntity;
use Symfony\Component\Form\AbstractType;
use App\Form\MyFormType;
use App\Form\MyFormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
class MyEntityType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder
->add('field1')
->add('field2', MyFormType::class)
->add('field3', MyFormType::class)
;
}
public function configureOptions(OptionsResolver $resolver)
{
$resolver->setDefaults([
'data_class' => …
```
=> Avoid duplicate "use" statement for FormType

src/Maker/MakeEntity.php
Hello,
When you want to create a field, for an entity, representing an uuid, if you name it `uuid` the maker will set the default type to `uuid`. Same for `guid`.
=> Added UUID and GUID default type to entity maker

src/Maker/MakeEntity.php
The deprecation message hints the Generator class, while the fifth argument is the EntityClassGenerator class
=> Wrong class in deprecation message in MakeEntity

src/Validator.php, tests/ValidatorTest.php
when create a reset-password at question `What email address will be used to send reset confirmations? e.g. mailer@your-domain.com` and we just enter without filling the answer it will thrown an exception 
```
Argument 1 passed to Symfony\Bundle\MakerBundle\Validator::validateEmailAddress() must be of the type string, null given, called in /path/vendor/symfony/console/Helper/QuestionHelper.php on line 468
```
there are 2 possible solution. 1. change the default value to empty string (this PR), or 2. make the `validateEmailAddress` argument nullable and check the value inside the method.
=> change from-email-address default value to empty string

CHANGELOG.md, composer.json
This was causting doctrine/inflector v2 to be installed. Then,
if a user required another package that only worked with v1 - like
doctrine/orm, that package would fail to install because the user's
app is locked on v2.
Dropping support for v2 isn't really a fix, but will make it more
compatible with the ecosystem at the current time. Later, especially
when doctrine/orm allows 2, we can again.
See also https://github.com/composer/composer/issues/8910
Note: I kept the v2 compatible code in the bundle for now.
Fixes #609
=> Dropping doctrine/inflector v2 support temporarily

src/Maker/MakeResetPassword.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Security/InteractiveSecurityHelper.php, tests/Maker/MakeResetPasswordTest.php, tests/Security/InteractiveSecurityHelperTest.php, tests/fixtures/MakeResetPasswordCustomUserAttribute/config/packages/security.yml, tests/fixtures/MakeResetPasswordCustomUserAttribute/src/Entity/UserCustom.php
Should fix #605 
And `guessEmailGetter` is smarter with the use of the custom email property
=> Make reset password - custom user entity

appveyor.yml, src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/registration/twig_email.tpl.php, src/Resources/skeleton/registration/twig_template.tpl.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php, src/Security/InteractiveSecurityHelper.php, tests/Maker/MakeRegistrationFormTest.php, tests/fixtures/MakeRegistrationFormEntity/tests/VerifyEmailDoesntModifyUserEntityTest.php, tests/fixtures/MakeRegistrationFormVerifyEmail/config/packages/security.yaml, tests/fixtures/MakeRegistrationFormVerifyEmail/src/Entity/User.php, tests/fixtures/MakeRegistrationFormVerifyEmail/tests/UserEntityTest.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/config/packages/mailer.yaml, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/config/packages/security.yaml, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/src/Entity/User.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/src/Repository/UserRepository.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/src/Security/LoginFormAuthenticator.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/tests/VerifyEmailTest.php
Adds support for email verification in `make:registration-form` by means of the Symfony Cast's Verify Email Bundle
closes #542
=> Implement email verification upon user registration 

src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
default to failing silently on a reset password request in the `ResetPasswordController`. This will prevent the actual cause of the failure (user throttle limit, unknown user, etc..) from being displayed. We also redirect to the check email route by default.
The user has the option to reveal the cause of the failure via a flash or, preferably, implementing a logging solution to store the error message.
=> redirect to check email route on failure

.travis.yml, src/Test/MakerTestEnvironment.php, src/Test/MakerTestProcess.php, tests/Maker/MakeMigrationTest.php
This avoids a behavior change in https://github.com/symfony/console/compare/6f533d9...d2c9f77 from symfony/symfony#37286
I'll create a PR to revert this after merge, which we will merge once the issue is resolved.
=> using stable-dev in tests to get latest fixes from Symfony

src/Resources/help/MakeForm.txt
Add information about the second argument (bound-class).
Give hints on using the bound-class with classes other than entities.
Improves on #301 and fixes #477
=> Docs: improve make:form helper

src/Util/YamlSourceManipulator.php, tests/Util/yaml_fixtures/add_comment_to_sequence.test
Previously, the reversed logic in the manipulator meant that this transformation *was* done correctly, but the manipulator then reported that the data had somehow gotten corrupt (because indexed keys weren't matching).
=> making sure comments on sequential lines work

composer.json, src/Console/MigrationDiffFilteredOutput.php, src/ConsoleStyle.php, src/Maker/MakeMigration.php, src/Test/MakerTestCase.php, src/Test/MakerTestDetails.php, src/Test/MakerTestEnvironment.php, tests/Maker/MakeMigrationTest.php
This more selectively overrides output so that some output - including
asking a confirmation question - can be shown to the user.
Fixes #643 and fixes #642
=> Fixing wrapping of doctrine:migrations:diff command

src/Docker/DockerDatabaseServices.php, src/Maker/MakeDockerDatabase.php, src/Resources/config/makers.xml, src/Util/ComposeFileManipulator.php, src/Util/YamlSourceManipulator.php, tests/Docker/DatabaseServicesTest.php, tests/Maker/FunctionalTest.php, tests/Maker/MakeDockerDatabaseTest.php, tests/Util/ComposeFileManipulatorTest.php, tests/Util/yaml_fixtures/find_value_after_comment_containing_value_string.test
Spin up a MySQL / MariaDB / Postgres database via docker compose! Whether you already use docker, or want to give it a try - `make:docker:database` will create or update a `docker-compose.yaml` in your projects root directory...
=> hello docker!

.travis.yml, src/Test/MakerTestEnvironment.php
They are too likely to break. Sometimes, in order for the
"dev" version of Symfony's stable branch to pass, we need
dev versions of other dependencies. Sometimes, we need the
exact opposite: dev versions of other libs cause failures.
=> avoiding stable-dev dependencies on CI

src/Docker/DockerDatabaseServices.php, tests/Maker/MakeDockerDatabaseTest.php
This adds the MYSQL_DATABASE environment variable to docker-compose.yaml, which enables Docker to create a default database called 'main'. This matches the symfony binary's default expected database.
=> Create 'main' database in Docker by default

src/Maker/MakeDockerDatabase.php, src/Maker/MakeResetPassword.php
| Q             | A
| ------------- | ---
| Branch?       | 5.1 (to be switched while merging)
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A
Following https://github.com/symfony/symfony/pull/36798. When running `bin/console` almost all the command descriptions do not end with a ".". So in order to be consistent, we should remove it from the Make Bundle Commands.
Thanks in again for your great work!
=> Remove trailing "." for consistency with #36798

src/Resources/skeleton/security/Voter.tpl.php
`$subject instanceof \App\Entity\BlogPost;` part replaced with `$subject instanceof \App\Entity\<?= str_replace('Voter', null, $class_name) ?>;` to better guess entity name based on Voter naming convention.
=> Better guess entity name in Voter template

src/Resources/skeleton/command/Command.tpl.php
This is follow-up for https://github.com/symfony/symfony/issues/35431
It would also align generated code with an example in the documentation.
https://symfony.com/doc/current/console.html#creating-a-command
=> Use Command:SUCCESS constant for command exit code when possible

src/Str.php
the capitalization in the wizard was confusing because Jelly Bean is two words and 'bean' was showing up lowercase.
=> swapping jellybean for popsicle

src/Resources/skeleton/resetPassword/twig_email.tpl.php
When no text template is specified, Symfony mailer converts the HTML template to text by stripping out the tags. This causes the text template to be malformed and includes references to links that don't exist. This PR adds a text template when requesting a password reset.
**Before:**
**After:**
=> Add text email for password reset request

src/Resources/skeleton/doctrine/Entity.tpl.php, tests/Util/fixtures/source/ProductWithTabs.php, tests/Util/fixtures/with_tabs/ProductWithTabs.php, tests/fixtures/MakeAuthenticatorLoginFormExistingController/src/Entity/User.php, tests/fixtures/MakeAuthenticatorLoginFormUserEntity/src/Entity/User.php, tests/fixtures/MakeAuthenticatorLoginFormUserEntityLogout/src/Entity/User.php, tests/fixtures/MakeAuthenticatorLoginFormUserEntityNoEncoder/src/Entity/User.php, tests/fixtures/MakeRegistrationFormEntity/src/Entity/User.php, tests/fixtures/MakeRegistrationFormNoGuessing/src/Entity/User.php, tests/fixtures/MakeRegistrationFormVerifyEmail/src/Entity/User.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/src/Entity/User.php
The [Doctrine](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/annotations-reference.html#id) and [Symfony](https://symfony.com/doc/current/doctrine.html#creating-an-entity-class) documentation (even after it explains how to use maker to create the entity) leaves them off.
I thought it would be nice if they matched.
=> Remove empty parenthesis

src/Maker/MakeAuthenticator.php, src/Resources/skeleton/authenticator/EmptyAuthenticator.tpl.php, src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
Added type-hints to `onAuthenticationSuccess` to support [changes](https://github.com/symfony/security-guard/commit/3105836b14bd984e9839a697ca9e65c2e6c7db8e) introduced in `symfony/security-guard 5.0`
=> Added type-hints to onAuthenticationSuccess

src/Maker/MakeResetPassword.php, src/Resources/config/makers.xml, src/Validator.php
The user's app might use either the new or old class. This is already handled correctly on DoctrineHelper.
Fixes #665
=> Fixing usage of legacy manager registry

src/Doctrine/EntityRegenerator.php
The tests are now mostly fixed, after a few vendor libraries implemented fixes.
However, there is still one test that's failing, and I'm unable to repeat it locally:
https://travis-ci.org/github/symfony/maker-bundle/jobs/721078624#L366
This started erroring between builds 2377 and 2380. No relevant changes were made to Maker, but there *were* some significant Doctrine vendor updates:
```
from: doctrine/persistence (1.4.x-dev 7faf8b7):
to:   doctrine/persistence (2.0.x-dev ebb6c32):
from: doctrine/doctrine-bundle (dev-master b74e72c):
to:   doctrine/doctrine-bundle (dev-master 78b13d5):
Summary: basically just the allowing of doctrine/persistence v2
from: doctrine/common (2.13.x-dev f3812c0):
to: doctrine/common (dev-master c799163):
```
The tl;dr is that something in doctrine/persistence …
=> Debugging CI Failure related to doctrine/persistence

src/Resources/skeleton/security/UserProvider.tpl.php
I propose to add the check if given class name is inherited from the User class (like the EntityUserProvider implementation does) to the UserProvider template.
Also I would follow up with a documentation PR reflecting that change in https://github.com/symfony/symfony-docs/blob/master/security/user_provider.rst
Or would it better to just add a info about this additional check to the documentation?
=> Support class inheritance in UserProvider::supportsClass by default

src/Util/ClassSourceManipulator.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/User.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php, tests/Doctrine/fixtures/expected_xml/src/Entity/UserXml.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_inverse.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_no_inverse.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_owning.php, tests/Util/fixtures/add_one_to_many_relation/User_simple.php, tests/Util/fixtures/add_one_to_many_relation/User_simple_orphan_removal.php, tests/Util/fixtures/add_one_to_many_relation/User_with_use_statements.php
Fixes https://github.com/symfony/maker-bundle/issues/673
**ManyToMany relations:**
_Before_:
_After_:
**OneToMany relations:**
_Before_:
_After_:
=> Issue673 Optimize removeElement method in doctrine entities

src/Resources/skeleton/controller/Controller.tpl.php
This sets the return type of the default `index()` method in a new controller generated by `make:controller`.
This is consistent with the various other controllers generated by the bundle.
=> [make:controller] Set index method return type

src/Resources/skeleton/serializer/Normalizer.tpl.php, tests/Maker/MakeSerializerNormalizerTest.php
Hi,
To fix https://github.com/symfony/maker-bundle/issues/395, I propose to do like in https://github.com/symfony/maker-bundle/pull/658. 
_This is only for Normalizer, because Voter was already fixed in https://github.com/symfony/maker-bundle/pull/658_
This intends to replace : https://github.com/symfony/maker-bundle/pull/416
=> #395 - guess entity name in normalizer template

.php_cs.dist
This meant that the tests/tmp was no longer being excluded.
Revert "Enhancement: Update PHP-CS-Fixer config"
This reverts commit 64a4f568b73253a0ea064660aa2a30c1e6678c45.
=> Reverting - exclude() needs to be relative to in().

.github/workflows/ci.yml
=> Enhancement: Do not install mysql-client, use the already installed one

.github/workflows/ci.yml
instead of 7.1.33
For reference see: https://github.com/symfony/maker-bundle/blob/ffaee624a20a462ec2da82942d3c9d8fc8dd1421/composer.json#L16
=> Enhancement: Based on composer.json we should test 7.1.3

.github/workflows/ci.yml, src/Test/MakerTestCase.php
skips styling tests in PHP 8 until cs tooling is available
=> skip cs related tests in PHP 8

src/Maker/AbstractMaker.php, src/Maker/MakeController.php, src/Maker/MakeCrud.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/skeleton/controller/Controller.tpl.php, src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
When using PHP8, Maker Bundle uses route attributes in the generated controllers instead of annotations.
- make:controller
- make:crud
- make:registration-form
- make:reset-password
As Doctrine/ORM does not currently have PHP8 support, we are unable to test the route functionality for `crud`, `registration-form`, & `reset-password`. No additional tests should be needed when Doctrine is PHP8 compatible.
=> php8 attributes support for generated controllers

.github/workflows/ci.yml
allows tests to run across all of the matrix's even if one matrix fails.
=> [CI] disable fail fast functionality

src/Util/ClassSourceManipulator.php
Worked around for the bug in `PHP-CS-Fixer` documented in issue #731
=> stop php-cs-fixer from complaining in CI

composer.json, src/Generator.php, src/Maker/AbstractMaker.php, src/Maker/MakeController.php, src/Maker/MakeCrud.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/config/services.xml, src/Util/PhpCompatUtil.php, tests/Command/MakerCommandTest.php, tests/Doctrine/EntityRegeneratorTest.php, tests/GeneratorTest.php, tests/Util/PhpVersionTest.php
Before we just checked the value of `\PHP_VERSION_ID` and passed a `bool` to templates that could use attributes. Now we've expended attribute support by checking if `composer.lock` has a platform override set. If not then we fall back to `\PHP_VERSION`
We've also introduced a new `PhpCompatUtil::class` & `use_attributes` is globally available to all templates.
=> improve php8 attribute support in makers

composer.json
This ensures that the package can be installed with `stable` as minimum stability.
=> Allow released versions of the deprecation contract

src/Maker/MakeDockerDatabase.php, src/Maker/MakeRegistrationForm.php, src/Util/YamlSourceManipulator.php, tests/Util/YamlSourceManipulatorTest.php
php-cs-fixer released an update which catches useless `sprintf()` calls. A couple were found and fixed.
refs https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5280
=> fix incorrect usage of sprintf

composer.json
due to incompatibilities with `doctrine/orm`, `doctrine/inflector` `v2` was dropped in #611. `orm` now supports inflector v2 as of https://github.com/doctrine/orm/pull/8147 which has been released.
closes #756
=> reinstate doctrine/inflector v2 support

src/Util/PhpCompatUtil.php, tests/Util/PhpVersionTest.php
=> only use attributes if PHP >= 8 && Symfony >= 5.2

src/Util/ClassSourceManipulator.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php, tests/Util/fixtures/add_one_to_one_relation/UserProfile_simple_inverse.php, tests/Util/fixtures/add_one_to_one_relation/UserProfile_simple_inverse_not_nullable.php
Hi :wave: 
This PR is a proposal for #195 for handling the new value (if nullable) in a OneToOne association.
The following code was not valid, it fails at `$user->getUserProfile()` if we call `UserProfile#setUser(null)`:
```php
class UserProfile
{
// ...
public function setUser(?User $user): self
{
$this->user = $user;
// set (or unset) the owning side of the relation if necessary
$newUserProfile = null === $user ? null : $this;
if ($user->getUserProfile() !== $newUserProfile) {
$user->setUserProfile($newUserProfile);
}
return $this;
}
}
```
The following code takes care of:
- unset the user profile of the previous User (`$this->user`) if we assign a nullable User
- set the profile to the new user, and prevent an infinite loop with `user->getUserProfile() !== $this`
```php
class …
```
=> fix(make:entity): handle new value if nullable in OneToOne association, close #195

tests/Command/MakerCommandTest.php
PhpUnit 8.5.13 throws
```
1) Symfony\Bundle\MakerBundle\Tests\Command\MakerCommandTest::testExceptionOnMissingDependencies
expectExceptionMessageRegExp() is deprecated in PHPUnit 8 and will be removed in PHPUnit 9. Use expectExceptionMessageMatches() instead.
```
- This PR uses the recommended assertion in `MakerCommandTest`
- Minor refactoring
=> [Tests] fixed deprecated phpunit expectation

src/Maker/MakeAuthenticator.php
The wrong quotes were used, causing `\n\n` to be printed to the terminal (instead of real newlines)
=> [make:auth] Fixed newline characters

src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/skeleton/registration/twig_email.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Resources/skeleton/resetPassword/twig_email.tpl.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
=> fix invalid expiresAt values for ResetPassword & VerifyEmail templates

src/Maker/MakeRegistrationForm.php, src/Resources/config/makers.xml, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php, tests/Maker/MakeRegistrationFormTest.php, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/config/packages/mailer.yaml, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/config/packages/security.yaml, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Controller/MyController.php, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Entity/User.php, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Repository/UserRepository.php, tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/tests/VerifyEmailTest.php
By passing the user id as an extra query param to `VerifyEmailHelper::generateSignature()` - users are able to verify their email address without being authenticated.
As a precautionary note, answering `no` to `Do you want to require the user to be authenticated to verify their email?` will allow anyone with the link generated by `VerifyEmailHelper` to validated that users email address. It should also be advised that answering `no` could possibly leak personally identifiable information in log files if the user `id` is changed to say, a users email address.
=> [make:registration] allow email verification without authentication

tests/Maker/MakeEntityTest.php, tests/Maker/MakeMigrationTest.php
This fixes some errors https://github.com/symfony/maker-bundle/runs/1670347498#step:13:28 because it is comparing strings and not iterables.
=> Use assertStringNotContainsString instead of assertNotContains

src/Test/MakerTestCase.php
Hi!
I was trying to use [`MakerTestCase`](https://github.com/symfony/maker-bundle/blob/a47408fa6e39034a5abe324a46f4e6733266267a/src/Test/MakerTestCase.php) and I'm finding some little things. 
In this case, `symfony/process` is being used under the src directory in two files:
- [src/Test/MakerTestProcess.php](https://github.com/symfony/maker-bundle/blob/a47408fa6e39034a5abe324a46f4e6733266267a/src/Test/MakerTestProcess.php#L14)
- [src/Test/MakerTestEnvironment.php](https://github.com/symfony/maker-bundle/blob/a47408fa6e39034a5abe324a46f4e6733266267a/src/Test/MakerTestEnvironment.php#L18-L19)
So trying to execute tests I'm getting: `Error: Class 'Symfony\Component\Process\Process' not found`
=> Move symfony/process dependency from require-dev to require

src/Test/MakerTestEnvironment.php
This fixes the broken PHP 8 tests, as they were using PHPUnit 7.5 (which doesn't support PHP 8).
This version is also proposed to the official recipes and will probably be merged shortly: https://github.com/symfony/recipes/pull/868
=> Fixed PHP 7.1.3 tests by using PHPUnit 8.5

src/Doctrine/DoctrineHelper.php
It make autocomplete more predictable and much better in some cases. For example I have entities `Invoice` and `InvoiceTransaction`, with sort first suggestion will be `Invoice` but now it can be `InvoiceTransaction` and you must press `TAB` and `BACKSPACE` several times to edit `Invoice` entity.
=> Sort doctrine entities for autocomplete

src/Maker/MakeResetPassword.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Resources/skeleton/resetPassword/twig_check_email.tpl.php
I missed this template in #770
=> [Reset-Password] use expiration translation in check email route

src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php, src/Maker/MakeAuthenticator.php, src/Maker/MakeCommand.php, src/Maker/MakeController.php, src/Maker/MakeCrud.php, src/Maker/MakeDockerDatabase.php, src/Maker/MakeEntity.php, src/Maker/MakeFixtures.php, src/Maker/MakeForm.php, src/Maker/MakeFunctionalTest.php, src/Maker/MakeMessage.php, src/Maker/MakeMessengerMiddleware.php, src/Maker/MakeMigration.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Maker/MakeSerializerEncoder.php, src/Maker/MakeSerializerNormalizer.php, src/Maker/MakeSubscriber.php, src/Maker/MakeTwigExtension.php, src/Maker/MakeUnitTest.php, src/Maker/MakeUser.php, src/Maker/MakeValidator.php, src/Maker/MakeVoter.php, src/MakerInterface.php, src/Resources/skeleton/command/Command.tpl.php
Sidekick of https://github.com/symfony/symfony/pull/39851
When run with Symfony < 5.3, the generated commands are made forward-compatible with 5.3+
=> Make commands compatible with LazyCommand

src/Security/UserClassBuilder.php, tests/Security/fixtures/expected/UserEntityEmailWithPassword.php, tests/Security/fixtures/expected/UserEntityUser_nameWithPassword.php, tests/Security/fixtures/expected/UserEntityUsernameNoPassword.php, tests/Security/fixtures/expected/UserEntityUsernameWithPassword.php, tests/Security/fixtures/expected/UserModelEmailWithPassword.php, tests/Security/fixtures/expected/UserModelUsernameNoPassword.php, tests/Security/fixtures/expected/UserModelUsernameWithPassword.php
Before this fix, static analyzers are complaining:
```
Return type (void) of method App\Entity\User::getSalt() should be compatible with return type (string|null) of method Symfony\Component\Security\Core\User\UserInterface::getSalt()
```
cc @chalasr
=> Enhancement: Fullfill interface and move comments to the method description

CHANGELOG.md, src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php, src/DependencyInjection/MakerExtension.php, src/Maker/MakeFunctionalTest.php, src/Maker/MakeTest.php, src/Maker/MakeUnitTest.php, src/Resources/config/makers.xml, src/Resources/help/MakeTest.txt, src/Resources/skeleton/test/ApiTestCase.tpl.php, src/Resources/skeleton/test/KernelTestCase.tpl.php, src/Resources/skeleton/test/PantherTestCase.tpl.php, src/Resources/skeleton/test/TestCase.tpl.php, src/Resources/skeleton/test/WebTestCase.tpl.php, tests/Maker/FunctionalTest.php, tests/Maker/MakeFunctionalTestTest.php, tests/Maker/MakeTestTest.php, tests/Maker/MakeUnitTestTest.php
Replaces #806.
As a result of discussions with @weaverryan, this PR introduces a new generic test maker. It allows creating unit (PHPUnit), integration/service (WebTestCase) and E2E/UI (PantherTestCase) tests.
`make:unit-test` and `make:functional-test` have been deprecated, but BC is preserved.
=> Add a new make:test command

src/Maker/MakeTest.php, src/Resources/help/MakeTest.txt, src/Resources/skeleton/test/KernelTestCase.tpl.php, src/Test/MakerTestCase.php, src/Test/MakerTestDetails.php, tests/Maker/MakeFunctionalTestTest.php, tests/Maker/MakeTestTest.php
This follows #807 - I played with it locally and had some minor tweaks :).
Cheers!
=> Tweaks to the new make:test

src/Maker/MakeAuthenticator.php
We were using the wrong `Str` camel case method to generate the username field variable for the authenticator template.
```diff
// class ACustomAuthenticator extends AbstractLoginFormAuthenticator
...
public function authenticate(Request $request): PassportInterface
{
- $Email = $request->request->get('email', '');
+ $email = $request->request->get('email', '');
...
}
```
=> [make:auth] fix user email field with capital `E`

.github/workflows/ci.yaml, .twig_cs.dist, composer.json, src/Test/MakerTestEnvironment.php, src/Test/MakerTwigRuleSet.php
- upgrade `twigcs` to version 5.x for PHP8 support. `twigcs` v4.x is required for PHP 7.1 support
- drops official support for Symfony 3.x in MakerBundle
=> drop symfony 3.x support && firm up PHP 8 tests

src/Maker/MakeAuthenticator.php, tests/GeneratorTest.php, tests/fixtures/MakeAuthenticatorLoginFormUserEntity/tests/SecurityControllerTest.php, tests/fixtures/MakeAuthenticatorLoginFormUserEntityLogout/tests/SecurityControllerTest.php, tests/fixtures/MakeAuthenticatorSecurity52LoginForm/tests/SecurityControllerTest.php
- fixed deprecated ReflectionType::__toString() (MakeAuthenticatorTest) Deprecated in PHP 7.1
- removes unneeded optional param - triggers required param order deprecation in PHP8 (GeneratorTest)
- handles Session deprecation's introduced in Symfony 5.3 in test suites
=> [make:auth] handle session deprecations in 5.3

src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/crud/templates/_delete_form.tpl.php
Starting in Symfony 5.3, `framework.http_method_override` defaults to `false`. This prevents CRUD form submission for `PUT`, `PATCH` &/or `DELETE` methods.  See symfony/recipes#892
~This PR conditionally sets  `http_method_override` to true when using `make:crud` if using Symfony 5.3+~
We stop using the `DELETE` method override in favor of using `POST` on the delete operation.
=> [make:crud] use POST method instead of DELETE

.github/workflows/ci.yaml
Use ubuntu 1804 for tests that rely on PHP `<7.4`. Github released base image `ubuntu-latest` which uses `ubuntu-20.04` - the 20.04 does not have PHP 7.0 - 7.3. Previously, `ubuntu-latest` was based on `ubuntu-18.04`
In maker this caused our stable tests against 7.1, .2 & .3 to fail with a PDO Driver Error. Which is ultimately because the base 18.04 image does not have the required PHP version.
=> [CI] run tests on ubuntu 18.04

.github/workflows/ci.yaml
Having a scheduled CI run will make it easier to track down upstream stream breaking changes. Especially when we don't have any push activity for days on end. 
As a side effect, this will also give us better insight into the state of the Symfony eco-system as a whole as maker bundle tests just about every Symfony package in a simulated "real life" application.
=> [CI] run CI at least once per day

src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php, src/Doctrine/DoctrineHelper.php, src/Maker/MakeEntity.php, src/MakerBundle.php
=> Fix compat with doctrine-bundle >=2.3

src/Maker/MakeVoter.php, src/Resources/skeleton/security/Voter.tpl.php
starting in Symfony 5.0 the abstract voter methods introduced type hints (https://github.com/symfony/symfony/commit/8c46b95ec2958cec3e3f7e6dab858c4c29b20770). We now conditionally generate the `string` type hint for the `$attribute` argument.
Minor cleanup of the maker itself.
=> [make:voter] generate type hints

src/Doctrine/EntityClassGenerator.php, src/Maker/MakeUser.php, src/Resources/skeleton/doctrine/Repository.tpl.php, src/Security/UserClassBuilder.php, tests/Maker/MakeUserTest.php, tests/Security/UserClassBuilderTest.php, tests/Security/fixtures/expected/UserEntityEmailWithPassword.php, tests/Security/fixtures/expected/UserEntityUser_nameWithPassword.php, tests/Security/fixtures/expected/UserEntityUsernameNoPassword.php, tests/Security/fixtures/expected/UserEntityUsernameWithPassword.php, tests/Security/fixtures/expected/UserModelUsernameNoPassword.php, tests/Security/fixtures/expected/legacy/UserEntityEmailWithPassword.php, tests/Security/fixtures/expected/legacy/UserEntityUser_nameWithPassword.php, tests/Security/fixtures/expected/legacy/UserEntityUsernameNoPassword.php, tests/Security/fixtures/expected/legacy/UserEntityUsernameWithPassword.php, tests/Security/fixtures/expected/legacy/UserModelEmailWithPassword.php, tests/Security/fixtures/expected/legacy/UserModelUsernameNoPassword.php, tests/Security/fixtures/expected/legacy/UserModelUsernameWithPassword.php, tests/fixtures/MakeUserEntityPasswordAuthenticatedUserInterface/tests/GeneratedEntityTest.php
Starting in Symfony 5.3 - PR https://github.com/symfony/symfony/pull/40267 introduces the new `PasswordAuthenticatedUserInterface` ~& `LegacyPasswordAuthenticatedUserInterface`~ aimed at decoupling passwords from the `UserInterface`.
- Generated `User` entity implements `PasswordAuthenticatedUserInterface` if it exists.
- Adds correct type hint to the generated `UserRepository::upgradePassword()` method.
Authentication related changes are handled in #824
// cc @chalasr
=> [make:user] user entities implement PasswordAuthenticatedUserInterface

tests/Util/yaml_fixtures/add_item_and_sort_natural.test
This case is the subject of issue #618 
Apparently this does work now, because it passes the test. Maybe it still is a good idea to extend this test so no bugs will creep in in the future
=> Extend Yaml manipulator add_item_and_sort test

src/Maker/MakeCommand.php, src/Resources/skeleton/command/Command.tpl.php, tests/Maker/MakeCommandTest.php
Console command attribute class renamed from `ConsoleCommand` => `AsCommand` https://github.com/symfony/symfony/pull/40556
closes #820
=> [make:command] lets use attributes if possible

.github/workflows/ci.yaml, src/Doctrine/EntityClassGenerator.php, src/Maker/MakeEntity.php, src/Resources/help/MakeEntity.txt, src/Resources/skeleton/doctrine/Entity.tpl.php, src/Resources/skeleton/doctrine/broadcast_twig_template.tpl.php, tests/Maker/MakeEntityTest.php
This PR adds a new `--broadcast` to the `make:entity` command. This generates the required template to use the broadcasting feature of UX Turbo, and also add the `#[Broadcast]` attribute to the generated entity.
=> Add support for Symfony UX Turbo

src/Maker/MakeDockerDatabase.php
Currently, `make:docker:database` only supports creating & manipulating `docker-compose.yaml` files. In the docker world however, it is common to have `docker-compose.yml` files. This PR adds support to manipulate existing `docker-compose`(`.yml`||`.yaml`) files.
When running this command without an existing compose file, `.yaml` will be used.
fixes #777
=> [MakeDocker] add support for .yml docker-compose files

.github/workflows/ci.yaml
Problem: In CI globally we were requiring `symfony/flex@dev-main` && in stable tests `symfony/flex` (versioned release). This caused tests to explode when `dev-main` was out of sync with `stable`.
Solution: Conditionally require `dev-main` || `stable` for `symfony/flex` depending on `SYMFONY_SKELETON_STABILITY`
=> [ci] fix incompatible flex branches globally vs tests

src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php, src/Doctrine/EntityRelation.php, src/Maker/MakeAuthenticator.php, src/Util/ClassSourceManipulator.php, src/Util/YamlSourceManipulator.php
sets the visibility modifier for class constants
=> set visibility on class constants

src/Resources/skeleton/serializer/Encoder.tpl.php
Since PHP 7.1 - class constants can have a visibility modifier. The Symfony coding standards require the visibility modifier to be set. 
`make:serializer:encoder` now defaults to the `public` modifier for the `FORMAT` const.
=> [make:serializer:encoder] set public constant visibility modifier

.github/workflows/ci.yaml, phpunit.xml.dist, src/Test/MakerTestDetails.php
`doctrine.dbal.server_version` is no longer available - set the server version explicitly in the dsn.
https://github.com/symfony/recipes/pull/939
=> [ci] set server version in dsn

CHANGELOG.md, src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php, tests/fixtures/MakeRegistrationFormVerifyEmailFunctionalTest/src/Security/LoginFormAuthenticator.php
Applies security fix for CVE-2021-21424 in newly generated authenticators created by MakerBundle in Symfony 3.x applications.
fixes #880
=> [security] fix cve-2021-21424 legacy Symfony 3.x + MakerBundle

src/Test/MakerTestEnvironment.php, tests/Doctrine/EntityRegeneratorTest.php
- removes `override_url` config logic (feature has was introduced && deprecated in doctrine-bundle 2.3)
- remove duplicate directory getter
- run generated projects `bin/phpunit` instead of "makers" `simple-phpunit`
- add return types to touched classes
=> [tests] housekeeping

src/Test/MakerTestDetails.php, src/Test/MakerTestEnvironment.php
Flex recipe now uses PHPUnit `9.5` for the `SYMFONY_PHPUNIT_VERSION` https://github.com/symfony/recipes/pull/952/files#diff-7e77caa90dde27086b747cb093fb643bbed3d7dbb37baa4fd81a992504d18d99R15
Updates the test environment to look for and remove `<server name="SYMFONY_PHPUNIT_VERSION" value="9.5" />` from the phpunit config. 
---
- disable the `_test` dbname suffix functionality in the test environment
=> [tests] bump symfony phpunit version for CI

src/Resources/skeleton/security/UserProvider.tpl.php, src/Security/UserClassBuilder.php, tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithPassword.php, tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithoutPassword.php, tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserModelWithPassword.php, tests/Security/fixtures/expected/UserModelWithoutPassword.php
This updates the makers for https://github.com/symfony/symfony/pull/41493 (where these methods are reintroduced to the interface for 5.3.1)
=> [make:user] Keep implementing deprecated username methods

src/Resources/skeleton/doctrine/Repository.tpl.php
encode is the wrong term symfony tries to remove. The paramter is also called $newHashedPassword in the PasswordUpgraderInterface
=> Use proper name for parameter of upgradePassword

src/Util/YamlSourceManipulator.php, tests/Util/yaml_fixtures/keys_with_simple_quotes.test
Fix bug reported in #796 : running ``make:message`` cannot find existing messages when configuring with quotes according to [documentation](https://symfony.com/doc/current/messenger.html#routing-messages-to-a-transport).
=> Fix keys not found when surrounded by quotes

tests/fixtures/MakeController/config/packages/framework.yaml
fixes 
```
1) Symfony\Bundle\MakerBundle\Tests\Maker\MakeControllerTest::testExecute with data set "controller_basic" (Symfony\Bundle\MakerBundle\Test\MakerTestDetails Object (...))
Error while running the PHPUnit tests *in* the project: 
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.
Testing Project Test Suite
E                                                                   1 / 1 (100%)
Time: 162 ms, Memory: 20.00 MB
There was 1 error:
1) App\Tests\GeneratedControllerTest::testController
LogicException: You cannot create the client used in functional tests if the "framework.test" config is not set to true.
/var/htdocs/tests/tmp/cache/maker_app_f06e46ebe75d42ea9e9b63872d47e20b5.x-dev/vendor/symfony/framework-bundle/Test/WebTestCase.php:52 …
```
=> [ci][make-controller] set framework.test in test env

src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/twig_template.tpl.php
fixes #905 - previously the generated registration form included a loop to display verify-email flash message regardless if the `SymfonyCasts/verify-email-bundle` was used. This PR only generates the loop if the user chooses to utilize the verify email bundle when running `make:registration`
=> [make:registration] conditionally generate verify email flash in template

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php
This makes `make:crud` compatible with Symfony Turbo by default.
=> [make:crud] send the proper HTTP status codes and use renderForm() when available

src/Maker/MakeEntity.php, tests/Maker/MakeEntityTest.php
I'll try to get the testsuite running. Then I will also write a test for that.
=> [make:entity] Fix error when API-Platform is installed.

tests/Doctrine/EntityRegeneratorTest.php
Hi!
Starting in Composer 2.1 & Symfony 5.3, whether the annotations system is auto-enabled depends on whether doctrine/annotations will be available *without* taking into account dev dependencies. In MakerBundle, when we boot a test container, doctrine/annotations is a dev dependency only (appropriately), which incorrectly hints to the container
that the system should not be initialized. So, we force it.
Cheers!
=> [CI] Fixes test error about missing annotation_reader

appveyor.yml, tests/Maker/MakeEntityTest.php
This fixes the final failure on AppVeyor, where we don't bother to setup Mercure. Testing this isn't really necessary, as it's covered in the Unix tests anyways - I think that's good enough.
=> [CI] Skip Mercure test if not setup

src/Generator.php, src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Util/TemplateComponentGenerator.php, tests/Util/TemplateComponentGeneratorTest.php
- Implements a new use statement sorter for templates
- use class properties instead of abusing command arguments
=> [make:registration] cleanup maker and template

CHANGELOG.md
Hi Makers!
Insert clever words here
*June 30th, 2021*
- [#895](https://github.com/symfony/maker-bundle/pull/895) - [make:crud] send the proper HTTP status codes and use renderForm() when available - *@dunglas*
- [#889](https://github.com/symfony/maker-bundle/pull/889) - [make:user] Use password_hashers instead of encoders - *@wouterj*
- [#913](https://github.com/symfony/maker-bundle/pull/913) - [make:registration] conditionally generate verify email flash in template - *@jrushlow*
- [#881](https://github.com/symfony/maker-bundle/pull/881) - [make:entity] Fix error when API-Platform is installed. - *@MichaelBrauner*
Diff: https://github.com/symfony/maker-bundle/compare/v1.32.0...v1.33.0
Happy making!
=> [release] v1.33.0

.github/workflows/ci.yaml, src/Test/MakerTestEnvironment.php, tests/Maker/MakeMigrationTest.php
- We don't have a `5.x` branch anymore on `symfony/symfony` - let's use the `dev` version specified in `versions.json` in place of the `5.x` branch.
- `SYMFONY_REQUIRE` env param in CI overrides the stability version specified for the run, resulting in a mixed set of versioned packages for each test. e.g. `symfony/http === v5.3.0` && `symfony/twig-bridge === v5.4.x-dev` even though `SYMFONY_SKELETON_STABILITY=dev` is set. 
- some symfony components now use `psr/log` `^1 || ^2 || ^3` but `doctrine/migrations` still uses `^1`. For migrations tests, because `doctrine/orm` is required after the skeleton has been built, there is a version conflict w/ the locked, `psr/log:2.0` and `doctrine/migrations`. Calling `psr/log:^1.1.4` resolves this issue and allows the tests to run.
_contains …
=> [ci] handle new 5.4 branch & make dev tests green

src/Generator.php, src/Resources/config/services.xml, src/Resources/skeleton/controller/Controller.tpl.php, src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Util/TemplateComponentGenerator.php, tests/Util/TemplateComponentGeneratorTest.php
Concept to cleanup templates that depend on route annotations / attributes for better DX when contributing to MakerBundle.
The `ResetPasswordController` is an exception due to the existing docBlocks that are generated. Will revisit that controller in the future.
=> [internal] add route generator for controllers

src/Generator.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Util/ClassNameDetails.php, src/Util/TemplateComponentGenerator.php
Use the new password hasher if it exists, or fallback to the old password encoder for `make:reset-password` & `make:registration`.
- introduces the concept of using `ClassNameDetails` objects in `make:registration` templates.
- adds a new `TemplateComponentsGenerator::getPropertyType($classNameDetails)` object that simplifies using typed properties in templates.
_contains `@legacy` tags for internal use:_
- Remove `Generator::getControllerBaseClass()` when `FrameworkBundle`  min supported version >= 4.1
- make:registration `$passwordHasher` conditional can be removed when min Symfony supported version >=5.3
- make:reset-password `$passwordHasher` conditional can be removed when min Symfony supported version >=5.3
- injected controller var's `password_variable_name` & `use_password_hasher` …
=> use password hasher for make:registration & make:reset-password, includes other improvements

tests/Maker/MakeMigrationTest.php
Removes legacy code thats not needed anymore.
=> [make:migration] remove legacy dependency in tests

src/Maker/MakeEntity.php
In a fix #482 json_array type was removed from using but it's available in a list of types. In section Other Types
=> [make:entity] Remove deprecated json_array type from available list types.

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/templates/edit.tpl.php, src/Resources/skeleton/crud/templates/new.tpl.php, src/Resources/skeleton/crud/templates/show.tpl.php
The maker CRUD allow to set a namespace in the controller name (example : `Admin\ArticleController`). In this case, maker create namespace and folders for the templates.
```
s.leblanc@cronos $ symfony console make:crud Article
Choose a name for your controller class (e.g. ArticleController) [ArticleController]:
> Admin\ArticleController
created: src/Controller/Admin/ArticleController.php
created: src/Form/ArticleType.php
created: templates/admin/article/_delete_form.html.twig
created: templates/admin/article/_form.html.twig
created: templates/admin/article/edit.html.twig
created: templates/admin/article/index.html.twig
created: templates/admin/article/new.html.twig
created: templates/admin/article/show.html.twig
```
The controller is OK, the render function is call with the good path : …
=> [make:crud] Fix templates path use in include

src/Doctrine/EntityRegenerator.php
fix union type spacing as flagged by php-cs-fixer
Symfony precedence - https://github.com/symfony/symfony/pull/41912/files
=> [ci] fix union type spacing

src/Doctrine/EntityRegenerator.php, src/Resources/skeleton/doctrine/Entity.tpl.php
Hi,
here is an update to use new `ApiResource` attribute from api platofrm v3 when providing `--api-resource` flag in `make:entity` command.
This cannot be tested yet since v3 is not released
=> [make:entity] APIP: use new attribute if exists

src/Generator.php, src/Util/PhpCompatUtil.php, tests/Util/PhpVersionTest.php
Hello,
what do you think if we make the method `PhpCompatUtil::getPhpVersion()` public?
This could be needed for some libs which leverage maker bundle
This would be helpful to resolve this problem: https://github.com/api-platform/core/pull/4423#pullrequestreview-747675271
Another solution for my problem would be to expose a global `is_php8` variable to all templates. but maybe that's not a good solution, because way _may_ need to differentiate minor versions
=> make PhpCompatUtil::getPhpVersion() public

src/Resources/skeleton/authenticator/Security52EmptyAuthenticator.tpl.php
refs: https://github.com/symfony/symfony/blob/1c1e2d96816166fdbe726ecc09716d07da90c06d/src/Symfony/Component/Security/Http/EntryPoint/AuthenticationEntryPointInterface.php#L24
=> Fixed typo in src/Resources/skeleton/authenticator/Security52EmptyAuthenticator.tpl.php

tests/Maker/MakeEntityLegacyTest.php, tests/Maker/MakeEntityTest.php
The test failing seems to be caused by https://github.com/symfony/recipes/pull/1007
=> Fix replacing default MERCURE_URL in tests

src/Test/MakerTestDetails.php
Ref: https://github.com/symfony/recipes/commit/b1b582b7326d4049e361b96d27b6fc28bb4f644a
tl;dr Our tests fail, because we are not manipulating the `.env` file correctly.
=> Updating test dsn for DATABASE_URL

src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
Fixes (by removing `Interface`) an unnecessarily long and strange argument name in the controller. Before:
Already tested in a real app to be extra safe :)
=> Renaming variable $userPasswordHasherInterface -> $userPasswordHasher

src/Doctrine/DoctrineHelper.php
=> Avoid iterating on null for DoctrineBundle 2.2 and lower

src/Util/YamlSourceManipulator.php
This PR fixes two pieces of code that trigger a deprecation error on PHP 8.1. You can see them in the CI output of #1012.
=> Fix PHP 8.1 deprecations

src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
DI the `EntityManagerInterface` into the constructor as the private method is ultimately called in https://github.com/symfony/maker-bundle/blob/63dc8ba1089f7ab7ae400b03dbee347f8b631275/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L41 as well as the public `reset` method as well.
=> [reset-password] fix missing entity manager di

src/Maker/MakeAuthenticator.php
=> preventing Guard auth method from exploding in 6.0

tests/Maker/MakeEntityTest.php
handles recipe change from https://github.com/symfony/recipes/pull/971 for `DoctrineBundle`
=> [tests] handle missing type config value for doctrine

src/Maker/MakeAuthenticator.php
=> Fixing wrong messaging in make:auth about checking password in final steps

tests/Maker/MakeSerializerEncoderTest.php, tests/Maker/MakeSerializerNormalizerTest.php
When running serializer tests in Symfony <= 5.3, composer attempts to use `symfony/serializer-pack@1.1` (The latest version at the time of this PR) which conflicts with `symfony/property-info` `<5.4`. This in turn causes our tests to fail due to an uninstallable set of packages. 
As a work around, until something better comes along, adding `symfony/serializer-pack:*` as an extra test dependency allows lesser version of `serializer-pack` to be used in the test without conflict with its underlying packages.
=> [ci] fix symfony serializer deps in ci

src/Resources/skeleton/authenticator/Security52EmptyAuthenticator.tpl.php
We either use `PassportInterface` or `Passport` below, but only add `PassportInterface` use statement
=> Add missing Passport use statement

tests/Maker/MakeFunctionalTestTest.php, tests/Maker/MakeTestTest.php
Panther `>= 2.x` only supports PHP >= `8.0`. We still need to use Panther `1.x` for PHP `7.x` tests until PHP 7 support is dropped in MakerBundle
=> [ci] allow panther <2.0 in tests

src/Test/MakerTestRunner.php
DoctrineBundle >= 2.4 Flex Recipe uses `when@test` in the `config/packages/doctrine.yaml` file instead of a separate `config/packages/test/doctrine.yaml` file. 
Prior to this PR we were removing the `test/doctrine.yaml` file because we did not want to use the `_test` database suffix in our tests. Now we remove the `dbname_suffix` property if it isset in the test environment. For BC, we still remove the `test/doctrine.yaml` file. 
We could remove then entire `when@test` property from `doctrine.yaml`, but it would probably be best to do this if something changes to the recipe in the future that warrants the removal. (Something may be added that we don't want to remove in the future as well.)
=> [ci] handle when@test for doctrine

src/Maker/MakeRegistrationForm.php, src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_class_attribute/User_empty.php, tests/Util/fixtures/add_class_attribute/User_simple.php
- fixes CI related MakeRegistrationFailures
- Adds support for class level attributes, specifically `UniqueEntity` attributes on the `User` entity.
- Adds support for VerifyEmail property attributes
Known Issues:
Adding a class level attribute that utilizes an aliased use statement, e.g. `use CLASS as PREFIX` type alias is not supported in this PR.
=> [MakeRegistration] add support for verify email attributes

.gitignore
After running tests the repo is in a dirty state - the `/fake` file is created in the root dir.
Also, I reordered `.gitignore` file here
=> Ignore fake file created after running tests and reorder .gitignore

src/Maker/MakeAuthenticator.php, src/Resources/config/makers.xml, src/Resources/config/services.xml, src/Security/SecurityControllerBuilder.php, tests/Security/SecurityControllerBuilderTest.php, tests/Security/fixtures/expected/SecurityController_login.php, tests/Security/fixtures/expected/legacy_add_login_logout_method/SecurityController_login_logout.php, tests/Security/fixtures/expected/legacy_add_login_method/SecurityController_login.php, tests/Security/fixtures/expected/legacy_add_logout_method/SecurityController_logout.php
=> [make:auth] fix security controller attributes

src/Util/ClassSourceManipulator.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/User.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php, tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php, tests/Doctrine/fixtures/expected_xml/src/Entity/UserXml.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_inverse.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_no_inverse.php, tests/Util/fixtures/add_many_to_many_relation/User_simple_owning.php, tests/Util/fixtures/add_many_to_many_relation/legacy/User_simple_inverse.php, tests/Util/fixtures/add_many_to_many_relation/legacy/User_simple_no_inverse.php, tests/Util/fixtures/add_many_to_many_relation/legacy/User_simple_owning.php, tests/Util/fixtures/add_one_to_many_relation/User_simple.php, tests/Util/fixtures/add_one_to_many_relation/User_simple_orphan_removal.php, tests/Util/fixtures/add_one_to_many_relation/User_with_use_statements.php, tests/Util/fixtures/add_one_to_many_relation/legacy/User_simple.php, tests/Util/fixtures/add_one_to_many_relation/legacy/User_simple_orphan_removal.php, tests/Util/fixtures/add_one_to_many_relation/legacy/User_with_use_statements.php
=> [make:entity] Change getter PHPDoc return type on Collection

src/Resources/skeleton/registration/twig_template.tpl.php
Hi,
I changed the case to be like the standard coding:
https://twig.symfony.com/doc/3.x/coding_standards.html
=> [verify-email] Coding standards - Twig

src/Test/MakerTestEnvironment.php
If users excluded `vendor/` dir in their global `.gitignore` - it will cause problems with tests, something like this:
```
4) Symfony\Bundle\MakerBundle\Tests\Maker\MakeResetPasswordTest::testExecute with data set "it_generates_with_custom_user" (Symfony\Bundle\MakerBundle\Test\MakerTestDetails Object (...))
Exception: Error running command: "php dep_runner.php". Output: "
Warning: require(/Users/victor/www/symfony/maker-bundle/tests/tmp/cache/maker_app_e9d3bad0858931812130f4a985c93519_current/vendor/autoload.php): failed to open stream: No such file or directory in /Users/victor/www/symfony/maker-bundle/tests/tmp/cache/maker_app_e9d3bad0858931812130f4a985c93519_current/dep_runner.php on line 3
Call Stack:
0.0001     403280   1. {main}() …
```
=> Force adding vendor/ to bypass global .gitignore

src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/skeleton/authenticator/Security52EmptyAuthenticator.tpl.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, src/Test/MakerTestRunner.php, src/Util/ClassSourceManipulator.php, tests/Maker/MakeEntityTest.php, tests/Maker/MakeFunctionalTestTest.php, tests/Maker/MakeResetPasswordTest.php, tests/Maker/MakeSerializerEncoderTest.php, tests/Maker/MakeSerializerNormalizerTest.php, tests/Maker/MakeTestTest.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_class_attribute/User_empty.php, tests/Util/fixtures/add_class_attribute/User_simple.php
If there's `Symfony\Contracts\Translation\TranslatorInterface` service available in the project - Maker will generate a slightly different controller's code to inject translator service and translate exception reasons out of the box.
Available after: https://github.com/SymfonyCasts/reset-password-bundle/pull/206
=> [make:reset-password] Translate exception reasons provided by ResetPasswordBundle

CHANGELOG.md
Hi Makers!
This release handles several bug fixes within MakerBundle and adds support for translating ResetPasswordBundle Exception messages, using constants instead of strings with `make:voter`, improved types for `Collection` getter methods in Entities, and support for attributes in `make:registration`!
Diff: https://github.com/symfony/maker-bundle/compare/v1.36.4...v1.37.0
Happy making!
---
*February 15th, 2022*
- [#1062](https://github.com/symfony/maker-bundle/pull/1062) - [MakeRegistration] add support for verify email attributes - *@jrushlow*
- [#1059](https://github.com/symfony/maker-bundle/pull/1059) - [make:reset-password] Translate exception reasons provided by ResetPasswordBundle - *@bocharsky-bw*
- [#1057](https://github.com/symfony/maker-bundle/pull/1057) - [Voter] Refactor …
=> [release] prep v1.37.0

src/Maker/MakeTest.php, src/Resources/skeleton/test/ApiTestCase.tpl.php
Following the work in progress in https://github.com/api-platform/core/pull/4556, ApiTestCase will be moved from ApiPlatform\Core\Bridge\Symfony\Bundle\Test to ApiPlatform\Symfony\Bundle\Test. The current file location will be deprecated in 2.7 and become invalid in 3.0 .
As recommended by @dunglas, this implementation is compatible with all versions of API Platform.
=> Update ApiTestCase to be compliant with ApiPlatform v3.0

tests/Maker/MakeRegistrationFormTest.php, tests/fixtures/make-registration-form/standard_setup/config/routes.yaml
Previously we were replacing the `config/routes.yaml` file generated by recipes with our own. This broke several tests when https://github.com/symfony/recipes/issues/1030 was resolved in Symfony 6. 
To better test against a "real" environment, we use the generated `routes.yaml` file and then append our static routes to it.
=> [ci] fix overriding entire route config

src/Doctrine/DoctrineHelper.php, src/Doctrine/EntityRegenerator.php, src/Resources/skeleton/validator/Validator.tpl.php
Hi!
I found some malformed `@var` typehint comments  in the code annd fixed them.
(This is my first PR)
=> [make:validator] Fix @var typehint comments

src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, tests/Maker/MakeRegistrationFormTest.php
Exception reasons were translated in https://github.com/SymfonyCasts/verify-email-bundle/pull/103 that allows us to translate them with Maker bundle out of the box if Translator is available.
This PR is similar to #1059 but for VerifyEmailBundle
=> [make:registration-form] Translate reasons for VerifyEmailBundle if translator available

src/Str.php, src/Test/MakerTestCase.php, tests/StrTest.php
This PR amends the route names generated by `make:controller` and `make:crud` by prepending them with `app_`.
This matches the route names generated by `make:auth` and `make:registration-form`.
=> [make:controller][make:crud] Make route names start with 'app_'

src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/doctrine/Repository.tpl.php, src/Util/TemplateComponentGenerator.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
#788
- Add new methods `add` and `remove` to repository template.
- Improve controller template to generate methods `new`, `edit` and `delete`.
- Fix test repository fixtures files according new methods.
=> [make:crud] Improve controller generation

src/Util/YamlSourceManipulator.php, tests/Util/yaml_fixtures/add_item_on_config_with_bind.test
We need to tweak a regex pattern, because at the moment if you try to update yaml with following config:
```
services:
_defaults:
autowire: true
autoconfigure: true
bind:
$tracer: 'something'
```
You will receive:
=> [YamlSourceManipulator] Tweak regex pattern for regex key

CHANGELOG.md
Hi Makers!
We've squashed a few bugs and have added a few improvements including support for translating exception reasons in VerifyEmailBundle, API Platform 3.0 compliant test cases, improved route names in generated CRUD / Controllers, and finally the ability to use generated repositories instead of the `EntityManagerInterface` in a few cases!
*February 24th, 2022*
- [#1076](https://github.com/symfony/maker-bundle/pull/1076) - [make:registration-form] Translate reasons for VerifyEmailBundle if translator available - *@bocharsky-bw*
- [#1015](https://github.com/symfony/maker-bundle/pull/1015) - Update ApiTestCase to be compliant with ApiPlatform v3.0 - *@laryjulien*
- [#1007](https://github.com/symfony/maker-bundle/pull/1007) - [make:controller][make:crud] Make route names start with …
=> [release] prep v1.38.0

src/Maker/MakeDockerDatabase.php, src/Util/ComposeFileManipulator.php
Hi,
For this PR I:
- Fix link for the Docker compose file ports
- Added color yellow for the database service name
=> [make:docker:database] Fix link docker compose file ports

.github/workflows/ci.yaml
use the latest version of `setup-php` && force composer `v2.2` for Symfony 4.4 / PHP 7.1 support. The latter to be reverted in the future.
=> [ci] use composer 2.2 for Symfony 4.4 compat

CHANGELOG.md
*April 21st, 2022*
- [#1088](https://github.com/symfony/maker-bundle/pull/1088) - Add `@extends` tag to Doctrine repository template. - *@hhamon*
- [#1080](https://github.com/symfony/maker-bundle/pull/1080) - [make:twig-extension] reference twig 3.x docs in generated extension - *@BahmanMD*
- [#1084](https://github.com/symfony/maker-bundle/pull/1084) - [make:docker:database] Fix link docker compose file ports - *@mdoutreluingne*
=> [git-released] v1.39.0

CHANGELOG.md
*April 22nd, 2022*
- [#1098](https://github.com/symfony/maker-bundle/pull/1098) - drop symfony 4.4 support bump minimum Symfony version to 5.4.7 - *@jrushlow*
=> [git-released] v1.40.0

composer.json
Because 5.4.7 simply doesn't exist for those packages, as Symfony no longer tags the packages when no changes have occured.
=> Lower symfony/finder & symfony/yaml requirements

CHANGELOG.md
*April 23rd, 2022*
- [#1102](https://github.com/symfony/maker-bundle/pull/1102) - Lower symfony/finder & symfony/yaml requirements - *@bobvandevijver*
=> [git-released] v1.40.1

src/Resources/skeleton/doctrine/Repository.tpl.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
fixes #1086
If the idea in the issue is validated, PR is ready 😃
=> change signature method add/remove repository

src/Resources/skeleton/authenticator/login_form.tpl.php
Change `username` to `userIdentifier`
=> [make:auth] use userIdentifier instead of username on login_form

src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_entity_field/User_simple_object.php, tests/Util/fixtures/add_entity_field/legacy/User_simple_object.php
Use object typehint when adding object entity fields.
=> Use object typehint when generating entities

src/Maker/MakeTest.php
Fixes #1092 
Here I do not see why we must have a version of php < 8.1 . This is what was causing the problem it seems to me, the condition passed in the else, so users with a version of php > 8.1 and API platform 2.6 had the wrong class path (`ApiPlatform\Symfony\Bundle\Test\ApiTestCase`).
I think here we just need to know whether the class exists or not. Future versions of API platform will warn about deprecation of this wrong class path `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase` from version 2.7 and become invalid in 3.0, as shown [here ](https://github.com/symfony/maker-bundle/pull/1015).
=> [make:test] Removal of the condition requiring a php version < 8.1

src/Maker/MakeController.php, src/Resources/config/makers.xml, tests/Maker/MakeControllerTest.php
Hi makers :wave: !
This PR allows to make controller when we can use PHP8 attributes without forcing to install `doctrine/annotation`
But we should be aware that currently, without `doctrine/annotation`, we don't have a nice flex recipe that enable routing annotation read on Controller folder.
See https://github.com/symfony/recipes/pull/916 for reference.
So maybe we should create the config/routes/annotation.yaml in case we can use attributes AND file does not exist ? WDYT ?
=> [make:controller] avoid require doctrine/annotation when can use attributes

src/Maker/MakeStimulusController.php, src/Resources/config/makers.xml, src/Resources/help/MakeStimulusController.txt, src/Resources/skeleton/stimulus/Controller.tpl.php, tests/Maker/MakeStimulusControllerTest.php, tests/fixtures/make-stimulus-controller/with_targets.js, tests/fixtures/make-stimulus-controller/without_targets.js
New Command to generate Stimulus Controller with targets and values.
**test_controller.js**
```
import { Controller } from '@hotwired/stimulus';
/*
* The following line makes this controller "lazy": it won't be downloaded until needed
* See https://github.com/symfony/stimulus-bridge#lazy-controllers
*/
/* stimulusFetch: 'lazy' */
export default class extends Controller {
static targets = ['errors']
static values = {
maxItems: Number,
}
// ...
}
```
Tickets #809
=> [make:stimulus-controller] New Stimulus controller Maker command

src/Doctrine/DoctrineHelper.php
=> make:entity Use the namespace instead of the full class name for MappingDriver

CHANGELOG.md
*May 4th, 2022*
- [#1110](https://github.com/symfony/maker-bundle/pull/1110) - [make:user] Don't add to passwork_hashers if default recipe is in use - *@nicolas-grekas*
- [#1109](https://github.com/symfony/maker-bundle/pull/1109) - Add missing types in code templates - *@nicolas-grekas*
- [#1107](https://github.com/symfony/maker-bundle/pull/1107) - [make:user] Legacy <= 5.3 & Doctrine Cleanup - *@jrushlow*
- [#1104](https://github.com/symfony/maker-bundle/pull/1104) - [make:auth] drop guard support and legacy code cleanup  - *@jrushlow*
- [#1075](https://github.com/symfony/maker-bundle/pull/1075) - [make:stimulus-controller] New Stimulus controller Maker command - *@JabriAbdelilah*
- [#1028](https://github.com/symfony/maker-bundle/pull/1028) - Add typed properties for make:reset-password …
=> [git-released] v1.41.0

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php, src/Resources/skeleton/crud/test/Test.tpl.php, tests/Maker/MakeCrudTest.php
Add tests for the controller methods.
Add necessary dependencies.
Closes #229
Edit by @jrushlow:
- Feature is experimental - We generate a minimum WebTestCase for generated CRUD. 
- Generating tests is on an opt-in basis _if_ the user has `test-pack` already installed. Otherwise we're not advertising this feature yet.
- Entity / Form Field guessing is not _fully_ implemented. "Setter" values other than `string` will not match the Entity's property types and must be manually changed.
- Tests (other than `testIndex()`) are all generated with `markTestIncomplete()` 
- Better integration w/ Panther, Fixtures, Foundry, etc... to come in future PR's
=> [make:crud][experimental] Add generated tests to make:crud

CHANGELOG.md
*May 9th, 2022*
- [#1114](https://github.com/symfony/maker-bundle/pull/1114) - [make:entity] _em will be private in ORM 3.0, use getEntityManager() - *@jrushlow*
- [#456](https://github.com/symfony/maker-bundle/pull/456) - Use prefix "is" for getters on boolean fields - *@MaximePinot*
- [#307](https://github.com/symfony/maker-bundle/pull/307) - [make:crud][experimental] Add generated tests to make:crud - *@ckrack*
- [#1115](https://github.com/symfony/maker-bundle/pull/1115) - [make:crud] fix broken controller with custom repository - *@jrushlow*
=> [git-released] v1.42.0

src/Maker/MakeController.php, src/Resources/skeleton/controller/Controller.tpl.php, tests/fixtures/make-controller/tests/it_generates_a_controller.php
Return a JsonResponse instead of a Response when json method is used in controller.
Failing tests not related, see #1118 for a fix
=> [make:controller] Return a JsonResponse instead of a Response with --no-template

src/Maker/MakeAuthenticator.php, src/Maker/MakeRegistrationForm.php
Fix errors when enable_authenticator_manager is not set and true is the default value (from Symfony 6)
Related to symfony/recipes#1085
=> Fix errors when enable_authenticator_manager is not set

src/Util/ClassSourceManipulator.php
This PR aims to handle enums as value.
It's purpose is to prevent the make;entity command to fail because of manual use of Enum in entity attributes.
It may help when Doctrine will support Enums natively.
=> [CSM] fix: Handle enum as values

CHANGELOG.md
*May 17th, 2022*
- [#1120](https://github.com/symfony/maker-bundle/pull/1120) - [make:controller] Return a JsonResponse instead of a Response with --no-template - *@l-vo*
- [#1117](https://github.com/symfony/maker-bundle/pull/1117) - [make:crud] adding repository counts for crud testRemove  - *@dr-matt-smith*
- [#1118](https://github.com/symfony/maker-bundle/pull/1118) - Fix errors when enable_authenticator_manager is not set - *@l-vo*
- [#1042](https://github.com/symfony/maker-bundle/pull/1042) - [CSM] fix: Handle enum as values - *@Geekimo*
=> [git-released] v1.43.0

.php-cs-fixer.dist.php, src/Doctrine/EntityDetails.php, src/Doctrine/EntityRegenerator.php, src/Doctrine/EntityRelation.php, src/FileManager.php, src/GeneratorTwigHelper.php, src/Maker/MakeAuthenticator.php, src/Maker/MakeEntity.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Maker/MakeUser.php, src/Renderer/FormTypeRenderer.php, src/Security/SecurityConfigUpdater.php, src/Security/SecurityControllerBuilder.php, src/Test/MakerTestCase.php, src/Util/AutoloaderUtil.php, src/Util/ClassDetails.php, src/Util/ClassNameDetails.php, src/Util/ClassNameValue.php, src/Util/UseStatementGenerator.php, src/Util/YamlSourceManipulator.php, tests/DependencyBuilderTest.php, tests/Maker/MakeMessageTest.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/ComposeFileManipulatorTest.php, tests/Util/UseStatementGeneratorTest.php, tests/Util/YamlSourceManipulatorTest.php
- adds the PHP 8 && PHPUnit 8.4 migration rulesets
- forces trailing commas in multiline parameter lists to improve diff readability. e.g.
```php
public function __construct(
private int $number,
private string $word,
)
```
I also added trailing line commas in multiline _argument_ lists and then reverted the commit. See commit https://github.com/symfony/maker-bundle/pull/1127/commits/352f951250cd7fda3c63996c8839cb8778e66e7a
If this we _should_ keep multiline trailing commas for args - I'll drop the commit that reverts it. Thoughts @weaverryan @OskarStark @wouterj ?
=> update php-cs-fixer ruleset for php8

src/Generator.php
you can use the following test cases in [GeneratorTest](https://github.com/symfony/maker-bundle/blob/main/tests/GeneratorTest.php) for a quick verification.
yield 'example_1' => [
'Foo\\Admin',
'Controller',
'Controller',
'App\Controller\Foo\AdminController',
'Foo\AdminController',
];`
yield 'example_2' => [
'Cool',
'Security\Voter',
'Voter',
'App\Security\Voter\CoolVoter',
'CoolVoter',
];`
=> [Generator] correct createClassNameDetails doc

src/Maker/MakeEntity.php, src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_entity_field/User_simple_ulid.php, tests/Util/fixtures/add_entity_field/User_simple_uuid.php
1. Currently `uuid` is offered as the default type when the field name is uuid, which breaks when the `symfony/uid` component is not installed. Now `guid` is used when `uuid` is not available.
2. Getters & setters for `uuid`/`ulid` types now have type hints added when generated.
=> [make:entity] Improve uid support

.github/workflows/ci.yaml, appveyor.yml
This is a better solution than #1145
=> [ci] we do not need to install flex globally anymore

src/Maker/MakeSubscriber.php, tests/Maker/MakeSubscriberTest.php
Use KernelEvents constant instead hardcoded event type in MakeSubscriber.
#744
=> [make:subscriber] Improve MakeSubscriber to use KernelEvents constant instead hardcoded event

CHANGELOG.md
*July 13th, 2022*
- [#1147](https://github.com/symfony/maker-bundle/pull/1147) - [make:entity] Property types, Types:: constant & type guessing - *@weaverryan*
- [#1139](https://github.com/symfony/maker-bundle/pull/1139) - [make:entity] Improve uid support - *@HypeMC*
- [#1129](https://github.com/symfony/maker-bundle/pull/1129) - [tests] bring test suite up to PHP8 standards - *@jrushlow*
- [#1128](https://github.com/symfony/maker-bundle/pull/1128) - improve PHP 8 support w/ rector, removes legacy code, deprecates unused methods - *@jrushlow*
- [#1126](https://github.com/symfony/maker-bundle/pull/1126) - drop annotation support with entities - *@jrushlow*
- [#1125](https://github.com/symfony/maker-bundle/pull/1125) - [csm] strict typing && legacy code removal - *@jrushlow*
- …
=> [git-released] v1.44.0

src/Maker/MakeRegistrationForm.php
Fixes #1151 
Need reviews to know if it is correct to use the [`addslashes()`](https://www.php.net/manual/fr/function.addslashes.php) function for fix escape text-strings here🙏
=> [make:registration-form] Fix escape text-strings

CHANGELOG.md
*July 26th, 2022*
- [#1136](https://github.com/symfony/maker-bundle/pull/1136) - use method add() instead of [] in collection adder-method - *@HKandulla*
- [#1154](https://github.com/symfony/maker-bundle/pull/1154) - [make:entity] remove empty parenthesis on `id` - *@jrushlow*
- [#1153](https://github.com/symfony/maker-bundle/pull/1153) - [make:registration-form] Fix escape text-strings - *@mdoutreluingne*
=> [git-released] v1.45.0

CHANGELOG.md
*September 13th, 2022*
- [#1181](https://github.com/symfony/maker-bundle/pull/1181) - [4.4] handle legacy Doctrine Persistence 
AnnotationDriver - *@jrushlow*
- [#1163](https://github.com/symfony/maker-bundle/pull/1163) - fix attribute support in symfony 4.4 applications - 
*@spyridonas*
=> [release] v1.39.1

src/Maker/MakeTwigComponent.php, src/Resources/config/makers.xml, src/Resources/skeleton/twig/Component.tpl.php, src/Resources/skeleton/twig/LiveComponent.tpl.php, src/Resources/skeleton/twig/component_template.tpl.php, tests/Maker/MakeTwigComponentTest.php, tests/fixtures/make-twig-component/tests/it_generates_live_component.php, tests/fixtures/make-twig-component/tests/it_generates_twig_component.php
Adds a maker for `symfony/ux-twig-component`/`symfony/ux-live-component`.
**Creating a _standard_ twig component:**
```bash
bin/console make:twig-component
The name of your twig component (ie NotificationComponent):
> Notification
Make this a live component? (yes/no) [no]: # (defaults to yes if symfony/ux-live-component installed)
> no
created: src/Twig/Components/NotificationComponent.php
created: templates/components/notification.html.twig
Success!
```
```php
// src/Twig/Components/NotificationComponent.php
<?php
namespace App\Twig\Components;
use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;
#[AsTwigComponent('notification')]
final class NotificationComponent
{
}
```
```twig
{# templates/components/notification.html.twig #}
<div{{ attributes }}>
</div>
```
---
**Creating a _live_ …
=> Add `make:twig-component` maker

.github/workflows/ci.yaml, tests/Maker/MakeEntityTest.php
- Partially reverts https://github.com/symfony/maker-bundle/pull/1180
- Handles https://github.com/symfony/recipes/pull/1124
=> [ci] handle Mercure recipe change

src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
I add [options ](https://symfony.com/doc/current/reference/forms/types/repeated.html#options) instead of writing to first_options and second_options.
=> [reset-password] use higher level "options" in ChangePasswordFormType.tpl.php

src/Maker/MakeEntity.php, tests/Maker/MakeEntityTest.php
I fixed #1198, but I don't know how launch tests suites easily, I don't have found documentation for that.
=> [make:entity] fix compatibility with api-platform 3.0

src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/doctrine/Repository.tpl.php, src/Util/TemplateComponentGenerator.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php, tests/fixtures/make-crud/SweetFoodRepository.php, tests/fixtures/make-crud/expected/WithCustomRepository.php
Instead of using an `add()` method in the repository, it's been renamed to `save()`. Logic behind the change is to not confuse with "add()" and item to a collection - we're "save()"ing an entity to persistence. 
Original work done by @bdaler in #1169 
fixes #1138 
fixes #788
=> [make:crud] use save instead of add repository methods

src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_setter/User_simple_null_type.php
=> [make:entity] Fix error while making blob in entity

src/Resources/skeleton/doctrine/Repository.tpl.php
The `save` function has been forgotten for `upgradePassword`
=> [make:crud] use save instead of add in `upgradePassword`

src/Maker/MakeTwigExtension.php
I think it would be interesting to put the Twig Extensions in a `src/Twig/Extension` folder rather than `src/Twig`. The idea is to do like the Twig Components.
=> [make:twig-extension] Change folder for Twig Extension

src/Resources/skeleton/registration/twig_email.tpl.php, tests/Maker/MakeRegistrationFormTest.php, tests/fixtures/make-registration-form/tests/it_generates_registration_form_with_verification.php
Twig is escaping the `signedUrl` provided by `VerifyEmailBundle` - we shouldn't do this in the template... 
Before:  (Note the `&amp;` separator in the query string)
```
http://localhost/verify/email?expires=1664884822&amp;id=1&amp;signature=TcUbEcrs7QXcxPdU%2Bb6OZVI%2FkcZ4gGq6JTvubDSG04o%3D&amp;token=g%2BOsXoKFi5iT73QjyezR74Rya1Gy8UtryhEMbmK%2FUB4%3D
```
Now:
```
http://localhost/verify/email?expires=1664884822&id=1&signature=TcUbEcrs7QXcxPdU%2Bb6OZVI%2FkcZ4gGq6JTvubDSG04o%3D&token=g%2BOsXoKFi5iT73QjyezR74Rya1Gy8UtryhEMbmK%2FUB4%3D
```
- Use the actual `app_anonymous` route instead of the profiler routes. (avoids noise when debugging)
- https://github.com/symfony/symfony/pull/47075 removed the `context` from rendered `TemplatedEmail` (allows for better serialization). We were using the …
=> [make:registration-form] render the raw signedUrl in the email template

CHANGELOG.md
*October 4th, 2022*
- [#1211](https://github.com/symfony/maker-bundle/pull/1211) - [make:twig-extension] Change folder for Twig Extension - *@seb-jean*
- [#1217](https://github.com/symfony/maker-bundle/pull/1217) - [make:registration-form] render the raw signedUrl in the email template - 
*@jrushlow*
- [#1210](https://github.com/symfony/maker-bundle/pull/1210) - [make:serializer] use empty string in str_replace - *@jrushlow*
- [#1209](https://github.com/symfony/maker-bundle/pull/1209) - [make:crud] use save instead of add in `upgradePassword` - *@seb-jean*
=> [git-released] v1.47.0

src/Maker/MakeTwigExtension.php, src/Resources/help/MakeTwigExtension.txt, src/Resources/skeleton/twig/Extension.tpl.php, src/Resources/skeleton/twig/Runtime.tpl.php
This PR introduce a way to generate a twig runtime linked to the twig extension via the `make:twig-extension` command
Fixes https://github.com/symfony/maker-bundle/issues/1222
For now I did not touch the test, just want to gather early feedbacks :)
=> Twig extension: create with a runtime class

src/Resources/skeleton/security/Voter.tpl.php
Setting type for $subject in Voter template so phpstan issue can be covered by default
```
------ ----------------------------------------------------------------- 
15     Method App\Security\Voter\TenantVoter::supports() has parameter  
$subject with no type specified.                                 
------ ----------------------------------------------------------------- 
```
=> [make:voter] Set type for subject in Voter template

src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php, src/Resources/skeleton/crud/test/Test.tpl.php
The generated repository class by `make:entity` doesn’t have method `add` actually.
So I replaced the method `add` by `save` in `crud/tests/Test.*.tpl.php`
=> [make:controller] replace repository method add by save

src/Maker/MakeRegistrationForm.php, src/Resources/config/makers.xml
In a console application, I have the following configuration:
```yaml
framework:
router: false
```
As the `MakeRegistrationForm` class need a `RouterInterface` to be constructed, I get the following error: `Symfony\Bundle\MakerBundle\Maker\MakeRegistrationForm::__construct(): Argument #3 ($router) must be of type Symfony\Component\Routing\RouterInterface, null given`
This PR aim to remove this dependency.
=> [make:registration] Make router optional in MakeRegistrationForm constructor

CHANGELOG.md
*November 14th, 2022*
- [#1221](https://github.com/symfony/maker-bundle/pull/1221) - [make:voter] Set type for subject in Voter template - *@N-M*
- [#1232](https://github.com/symfony/maker-bundle/pull/1232) - [make:entity] Minor: Consistent output formatting - *@ThomasLandauer*
- [#1227](https://github.com/symfony/maker-bundle/pull/1227) - [make:registration] Make router optional in MakeRegistrationForm constructor - *@odolbeau*
- [#1226](https://github.com/symfony/maker-bundle/pull/1226) - [make:controller] replace repository method add by save - *@bechir*
=> [git-released] v1.48.0

src/Resources/skeleton/registration/twig_template.tpl.php
Errors messages are not displayed on registration form. This PR add the required things in TWIG template to display errors when availables.
=> [make:registration-form] Print registration form errors

src/Maker/MakeAuthenticator.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php
Closes #1231
As suggested in https://github.com/symfony/maker-bundle/issues/1231#issuecomment-1321891623
=> Improve error messages to show PHP & XML configurations are not supported

src/Security/SecurityConfigUpdater.php, tests/Security/SecurityConfigUpdaterTest.php, tests/Security/yaml_fixtures/expected_form_login/form_login.yaml, tests/Security/yaml_fixtures/expected_json_login/json_login.yaml, tests/Security/yaml_fixtures/expected_logout/logout.yaml
Adds missing tests for the `formLogin` & `logout` updaters. Adds a new updater for `jsonLogin` to be used in `make:security:json-login` #1246
=> Add tests for `SecurityConfigUpdater`

src/Test/MakerTestEnvironment.php, src/Test/MakerTestRunner.php, tests/Command/MakerCommandTest.php, tests/Maker/MakeEntityTest.php
Instead of copying MakerBundle to the flex skeleton and fiddling with autoloader to force things to work. Let's:
- add MakerBundle as a "path" repository to the skeletons `composer.json`
- `composer require --dev symfony/maker-bundle`
- Symlink Maker's `src/` to the skeleton's `vendor/symfony/maker-bundle/src` directory so we can test changes locally without having to create a commit.
Caveats:
- In Windows, `git clone` and symlinks are problematic. I experienced problems creating a symlink in the skeleton then attempting to clone the skeleton for individual maker tests. Workaround: `composer require --dev symfony/maker-bundle` + create the symlink each time we generate a "project" from the `flex_skeleton` 
- Windows AppVeyor test times have a ~4 min increase across the whole suite. This …
=> [tests] use composer to require maker bundle in tests

src/Maker/MakeMigration.php, src/Resources/config/makers.xml, tests/Maker/MakeMigrationTest.php
Makes the output of make:migration more consistent with other commands.
Before:
After:
=> [make:migration] Add link to new migration files

src/Maker/MakeController.php, tests/Maker/MakeAuthenticatorTest.php, tests/Maker/MakeControllerTest.php, tests/fixtures/make-auth/annotations.yaml, tests/fixtures/router-annotations.yaml
Attribute support for `make:controller` was added in https://github.com/symfony/maker-bundle/pull/725. 
PHP 7 support was dropped in https://github.com/symfony/maker-bundle/pull/1122
Attributes are always used when using PHP 8...
=> [make:controller] doctrine/annotations is not needed

tests/Maker/MakeRegistrationFormTest.php, tests/fixtures/make-registration-form/standard_setup/src/Controller/TestingController.php
IIRC we used a `yaml` router config in tests to avoid recipe changes / `doctrine/annotations` problems - this should no longer be a problem as we don't support annotations in maker. So let's be a bit more realistic in our tests and just use route attributes...
=> [make:registration-form] use route attributes for test routes

src/Maker/MakeRegistrationForm.php, src/Util/ClassDetails.php, tests/Util/ClassDetailsTest.php
MakerBundle is moving to 0 annotation support...
=> [make:registration-form] use UniqueEntity attribute instead of annotation

src/Maker/MakeCrud.php
The `sensio/framework-extra-bundle` is abandoned and replaced by built-in feature of symfony components. So this dependency is not required when using symfony 6.2+.
I've tested the crud maker on a new symfony 6.2 project without the framework-extra-bundle and the controller typehints work correctly
See: https://symfony.com/blog/new-in-symfony-6-2-built-in-cache-security-template-and-doctrine-attributes
=> [make:crud] Make sensio/framework-extra-bundle an optional dependency

src/Maker/MakeMigration.php
Related to issue #1274
- Change message when required package for migration doesn't exist.
=> [make:migration] Change message when required package for migration doesn't exist.

src/Maker/MakeAuthenticator.php
When using make:authenticator on a Symfony 6.2 project the generated code is deprecated.
In the generated code, `use Symfony\Component\Security\Core\Security;` should be replace by  `use Symfony\Bundle\SecurityBundle\Security;`.
However, in order to respect the compatibility with 5.4 I used a workaround.
=> [make:authenticator] Core\Security or SecurityBundle\Security - Avoid deprecations in 6.2

.github/workflows/ci.yaml
- use ubuntu `latest` os images. `ubuntu-18.04` is no longer available
=> [ci] fix stalled CI runs

src/Resources/skeleton/registration/RegistrationController.tpl.php
When launching the `make:registration-controller`, there is a `$request->get('id')` in the generated controller.
Replace `$request->get('id')` with `$request->query->get('id')` in the RegistrationController template to avoid using the Symfony internal method.
=> [make:registration-form] avoid using internal method get from Request

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php
The old `use_render_form` is always true, in both Symfony 5.4 and 6.2 so we always end un with a `$this->renderForm() ` that has been deprecated in 6.2.
This (ugly, but nevertheless working) hack tests if `getDoctrine` exists in AbstractController allows us to determine Symfony's version and if we should generate a `$this->render()` or a `$this->renderForm()`.
=> [make:crud] render or renderForm - Avoid deprecations in 6.2

composer.json
`v5.4.17` of `phpunit-bridge` fixed compatibility with `doctrine/annotations:^2.0`.
https://github.com/symfony/symfony/pull/48718/files#diff-7b61897762550adef47d038e61dbb44e9759b80179c8c7674fc2300c207fe751
Without the version bump to at least `5.4.17` - CI fails against `5.4.*` w/ `--prefer-lowest` dependencies. `phpunit-bridge:^5.4.7` is the lowest, but not compatible w/ MakerBundle as `doctrine/annotations` isn't needed.
Fixes:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() 
in /home/runner/work/maker-bundle/maker-bundle/vendor/symfony/phpunit-bridge/bootstrap.php:34
```
in several tests.
=> bump phpunit-bridge version constraint

src/Maker/MakeCrud.php
The recently merged pr #1272 did not correct the use_render_form because of a typo in the Kernel Version Id
=> [make:crud] fix typo in Kernel::VERSION usage

src/Resources/skeleton/doctrine/Repository.tpl.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
Store the entity manager in a variable rather than calling getEntityManager() twice in case of persist + flush
=> Fix(Doctrine Repository template)/Avoid potential double call in save method

src/Maker/MakeCrud.php, src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php, src/Resources/skeleton/crud/test/Test.tpl.php, src/Resources/skeleton/doctrine/Repository.tpl.php, src/Util/TemplateComponentGenerator.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php, tests/Maker/MakeCrudTest.php, tests/fixtures/make-crud/SweetFoodRepository.php, tests/fixtures/make-crud/expected/WithCustomRepository.php, tests/fixtures/make-crud/expected/WithCustomRepositoryLegacy.php
Fix #1327
In this PR I've removed the `save` and `remove` methods from the repositories, for the reasons explained here #1327.
( The add method has been renamed to save, here #1204 )
Reviews welcome!
=> [WCM] Deleting `save` and `remove` methods from repositories

src/Resources/skeleton/doctrine/Repository.tpl.php
Adding the @implements phpdoc tag on generated Doctrine repository classes will help IDE and prevent tools like phpstan from generating errors.
@implements is only added if `$with_password_upgrade` is set to true, avoiding useless phpdocs.
Similar to #1088
=> Add conditional @implements tag to Doctrine repository template

src/Maker/MakeEntity.php
Reason: In `date (or date_immutable)`, the second option looks inferior/exotic. So I changed it to look more equal: `date or date_immutable`
=> MakeEntity: Removing parentheses in field types overview

src/Maker/MakeAuthenticator.php, src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php, src/Resources/skeleton/authenticator/login_form.tpl.php, src/Security/SecurityConfigUpdater.php, tests/Maker/MakeAuthenticatorTest.php, tests/Security/SecurityConfigUpdaterTest.php, tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls_and_always_remember_me.yaml, tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls_and_remember_me_checkbox.yaml
Fix #848 
@weaverryan in #848:
> EDIT: And I wonder if we should even ask "Do you want to support remember me?" during this process? We could then ask "Do you want remember me to be activated via a checkbox or always activated"? We could use this to determine how the template is generated AND to automatically add the correct remember_me config to security.yaml.
=> [make:auth] Add `RememberMeBadge`

src/Util/ClassSourceManipulator.php
Setting a default value will lead to a wrong (not nullable) return value of the getter method.
Also setting a default value on a nullable field somehow cancels out the intention of nullable (except for setting it explicitly).
I'm not sure if this should be treated as a bc break. but since no existing properties are overwritten i think it should be fine.
=> [make:entity] don't set array field default value for nullable column

src/Util/UseStatementGenerator.php, tests/Util/UseStatementGeneratorTest.php
Follow https://github.com/symfony/maker-bundle/pull/1328#discussion_r1242695471
Following weaverryan's idea I've improved `UseStatementGenerator` in this PR to ignore duplicates.
=> Ignore use statement generator duplicates

src/Maker/MakeController.php, src/Resources/skeleton/controller/Controller.tpl.php, tests/Maker/MakeControllerTest.php, tests/fixtures/make-controller/tests/it_generates_an_invokable_controller.php
Allows to create invokable controllers [as described in the documentation](https://symfony.com/doc/current/controller/service.html#invokable-controllers).
=> Add `--invokable` option to `make:controller`

src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php, src/Maker/MakeAuthenticator.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Maker/MakeStimulusController.php, src/Security/SecurityConfigUpdater.php, src/Util/YamlSourceManipulator.php, src/Validator.php
Hello,
I found some places were there is unused variables, unused argument or unnecessary check .
As is my first PR on this repository, let me know if I miss something !
=> Remove unecessary code

src/Resources/skeleton/command/Command.tpl.php
I understand that this was not put on purpose, but I believe that it would be useful for most people, because when generating a lot of commands, in 99% of cases I have to manually write this generic code to be able to do dependency injection
=> Create empty-ready construct on command generate

src/Maker/MakeAuthenticator.php, src/Maker/MakeCommand.php, src/Maker/MakeController.php, src/Maker/MakeCrud.php, src/Maker/MakeDockerDatabase.php, src/Maker/MakeEntity.php, src/Maker/MakeFixtures.php, src/Maker/MakeForm.php, src/Maker/MakeFunctionalTest.php, src/Maker/MakeMessage.php, src/Maker/MakeMessengerMiddleware.php, src/Maker/MakeMigration.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeSerializerEncoder.php, src/Maker/MakeSerializerNormalizer.php, src/Maker/MakeStimulusController.php, src/Maker/MakeSubscriber.php, src/Maker/MakeTest.php, src/Maker/MakeTwigComponent.php, src/Maker/MakeTwigExtension.php, src/Maker/MakeUnitTest.php, src/Maker/MakeUser.php, src/Maker/MakeValidator.php, src/Maker/MakeVoter.php
Update command descriptions to enforce Symfony code conventions ([imperative mood](https://symfony.com/doc/current/contributing/code/conventions.html#naming-commands-and-options)) 
Not sure if MakerBundle follow Symfony codebase code conventions..  but as this bundle is used in the official documentation and many tutorials, it may be more coherent for the user
See: https://symfony.com/doc/current/contributing/code/conventions.html#naming-commands-and-options
=> [CS] Update command descriptions (minor)

src/Maker/MakeTwigComponent.php, src/Resources/skeleton/twig/Component.tpl.php, src/Resources/skeleton/twig/LiveComponent.tpl.php, tests/Maker/MakeTwigComponentTest.php, tests/fixtures/make-twig-component/tests/it_generates_live_component.php, tests/fixtures/make-twig-component/tests/it_generates_twig_component.php
Use the new default HTML syntax 
( `<twig:Alert />` instead of  `{{ component('Alert') }}` )
cc @weaverryan
=> Use TwigComponent HTML syntax

src/Validator.php, tests/ValidatorTest.php
Resolving issue when Absolute namespace for Entity is not passing through validation even if it should.
https://github.com/symfony/maker-bundle/issues/1365#issuecomment-1757938060
=> Entity Validator is accepting absolute namespaces

src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php, src/DependencyInjection/MakerExtension.php, src/Maker/MakeListener.php, src/Maker/MakeSubscriber.php, src/Resources/config/makers.xml, src/Resources/help/MakeListener.txt, src/Resources/skeleton/event/Listener.tpl.php, tests/Maker/MakeListenerTest.php, tests/Maker/MakeSubscriberTest.php, tests/fixtures/make-listener/tests/EventListener/CustomListener.php, tests/fixtures/make-listener/tests/EventListener/FooBarListener.php, tests/fixtures/make-listener/tests/EventListener/FooListener.php, tests/fixtures/make-listener/tests/EventListener/UnknownListener.php, tests/fixtures/make-listener/tests/EventSubscriber/CustomSubscriber.php, tests/fixtures/make-listener/tests/EventSubscriber/FooBarSubscriber.php, tests/fixtures/make-listener/tests/EventSubscriber/FooSubscriber.php, tests/fixtures/make-listener/tests/EventSubscriber/UnknownSubscriber.php
Related to #1301 I also suggest to add a global maker for both, Listener and Subscriber.
I worked with the based class `MakeSubscriber` and updated it to make this solution.
In the terminal you can run `make:event` and a question will be displayed like that to know which event class you want to create.
```
$ php bin/console make:event FooBar kernel.request
What event class to generate(enter ? to see all types) [Subscriber]:
> ?
Event Types Class
* Subscriber
* Listener
What event class to generate(enter ? to see all types) [Subscriber]:
> 
```
And if you write well what you want as `FooBarSubscriber` or `FooBarListener` and the event to listen, your file will be generated as Listener or Subscriber.
```php
namespace App\EventListener;
use …
```
=> [make:listener] Add global command for listener and subscriber

src/Util/MakerFileLinkFormatter.php, tests/FileManagerTest.php, tests/Util/MakerFileLinkFormatterTest.php
=> make the MakerFileLinkFormatter compatible with Symfony 7

src/Validator.php
Related to #1380 
In the `generate method`  we call the `Generator class` and the method  `createClassNameDetails`.
```
$entityClassDetails = $generator->createClassNameDetails(
$input->getArgument('name'),
'Entity\\'
);
```
And in this method we call the static method `validateClassName` of the `Validator class`.
In it we already have a check about the reserved keywords.
```
$reservedKeywords = ['__halt_compiler', 'abstract', 'and', 'array',
'as', 'break', 'callable', 'case', 'catch', 'class',
'clone', 'const', 'continue', 'declare', 'default', 'die', 'do',
'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor',
'endforeach', 'endif', 'endswitch', 'endwhile', 'eval',
'exit', 'extends', 'final', 'finally', 'fn', 'for', 'foreach', 'function',
'global', 'goto', 'if', 'implements', …
```
=> Add collection as reserved keywords

src/Resources/doc/index.rst
SensioGenerator was archived years ago, there's not much of a reason to even mention it.
=> remove references to SensioGenerator

CHANGELOG.md, src/Doctrine/EntityDetails.php, src/Renderer/FormTypeRenderer.php, src/Resources/skeleton/form/Type.tpl.php, tests/Maker/MakeFormTest.php, tests/fixtures/make-form/Property.php, tests/fixtures/make-form/relation_many_to_many/Book.php, tests/fixtures/make-form/relation_many_to_many/Library.php, tests/fixtures/make-form/relation_one_to_many/Author.php, tests/fixtures/make-form/relation_one_to_many/Book.php, tests/fixtures/make-form/relation_one_to_one/Librarian.php, tests/fixtures/make-form/relation_one_to_one/Library.php, tests/fixtures/make-form/tests/it_generates_form_with_many_to_many_relation.php, tests/fixtures/make-form/tests/it_generates_form_with_many_to_one_relation.php, tests/fixtures/make-form/tests/it_generates_form_with_one_to_many_relation.php, tests/fixtures/make-form/tests/it_generates_form_with_one_to_one_relation.php
PR for #1372 
When generating a form for an entity (through `make:form` or `make:crud`), this feature adds an EntityType input for each compatible relations in the generate form.
=> Add relations to entity form generation

src/Doctrine/EntityDetails.php, src/Maker/MakeCrud.php, src/Test/MakerTestEnvironment.php
Lately CI checks fail because of an [upgrade of the default phpunit version used in phpunit-bridge](https://github.com/symfony/symfony/pull/50760). This PR fixes this in the bundle's tests. And also a couple of minor cs fixes.
(EDIT: just noticed the CS part was fixed in #1397 just earlier)
=> Fix tests CS violations

src/Maker/MakeValidator.php, src/Resources/skeleton/validator/Validator.tpl.php
Currently, if you are using phpstan in your project you'll get
> Access to an undefined property Symfony\Component\Validator\Constraint::$message
error on any new generated validator
=> Proper annotation for generated validator constraint

.github/workflows/ci.yaml, composer.json, src/Security/SecurityControllerBuilder.php, src/Util/ClassSourceManipulator.php, src/Util/PrettyPrinter.php, tests/Util/ClassSourceManipulatorTest.php
This PR adds compatibility for dependency `nikic/php-parser` v5. 
Not sure if it works without additional changes, lets see if the tests will succeed.
**Edit:** Looks like a new major (or at least minor) version is required in order to make it compatible with v5, because v4 will not be compatible anymore.
**Edit2:** I did some refactoring and now it is working with v4 and v5.
=> Compatibility to dependency php parser v5

src/Resources/skeleton/doctrine/Fixtures.tpl.php
Using the command `make:fixtures` I noticed an extra semicolon in the generated file 
```
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
;
```
=> Doctrine make:fixtures - Remove extra semicolon

src/Resources/skeleton/doctrine/Repository.tpl.php
Added extra space character to keep the code style consistent.
Without this space, the new UserRepository is generated like this:
=> fix missing blank space in Repository.tpl.php

src/GeneratorTwigHelper.php, src/Resources/skeleton/controller/twig_template.tpl.php
TwigBridge's `CodeExtension` was made `@internal` via https://github.com/symfony/twig-bridge/commit/76b43934b95308231fc82a4905fb10eeac31b310
- removes file link anchor in generated template to the controller and template
- deprecates `GeneratorTwigHelper::getFileLink()`
fixes #1415
=> [make:controller] remove CodeExtension::getFileLink() call when generating twig templates

CHANGELOG.md
*February 1st, 2024*
- [#1423](https://github.com/symfony/maker-bundle/pull/1423) - [dx] drop twig 2.x support && open the door for 4.x - *@jrushlow*
- [#1417](https://github.com/symfony/maker-bundle/pull/1417) - Compatibility to dependency php parser v5 - *@drieschel*
- [#1414](https://github.com/symfony/maker-bundle/pull/1414) - Proper annotation for generated validator constraint - *@zorn-v*
- [#1407](https://github.com/symfony/maker-bundle/pull/1407) - New Name of Docker compose file - *@Xbirdfr*
- [#1419](https://github.com/symfony/maker-bundle/pull/1419) - [make:controller] remove CodeExtension::getFileLink() call when generating twig templates - *@jrushlow*
- [#1403](https://github.com/symfony/maker-bundle/pull/1403) - Doctrine make:fixtures - Remove extra semicolon - *@MrYamous*
- …
=> [git-released] v1.53.0

.gitignore, composer.json, phpunit.xml.dist, src/Test/MakerTestCase.php, src/Test/MakerTestDetails.php, tests/Maker/MakeEntityTest.php
- deprecates `MakerTestDetails::skipOnSymfony7()` methods that were meant to be used internally.
- add ability to skip tests locally (e.g. mercure tests can be skipped by setting `MAKER_SKIP_MERCURE_TEST` to `true` in `phpunit.xml`. Previously that var had to be set in the `$_SERVER` super global.) This plays into Windows tests on GitHub actions.
- fix outdated / deprecated `phpunit.xml.dist` schema / attributes
- require PHPUnit 9.6+ in tests (Only have to worry about 1 phpunit.xml schema. )
- adds a `MakerTestDetails::skipTest()` method & logic to replace the now deprecated `skipOnSymfony7()` methods. Ideally, we'll keep the new method for future use even if we're not using it now. `skipTest()` is marked `@internal` for the time being.
=> [dx] require >= PHPUnit 9.6, update phpunit schema, deprecate skipOnSymfony7() 

src/EventRegistry.php
The current events map is missing some events, such as the `command.signal` event. It also references some legacy event classes, like the `GetResponseEvent` class, which are no longer necessary since the minimum required version does not support these classes anymore.
This PR modifies the `EventRegistry` so that the events map is determined dynamically. The added benefit of this approach is that only the events that are actually available are listed.
=> Determine events map dynamically

src/Maker/MakeCrud.php
Hi! Noticed an extra dot after a question mark in tests question
```
Do you want to generate tests for the controller?. [Experimental] (yes/no) [no]:
```
=> [make:crud] Remove extra dot

src/Util/TemplateLinter.php
- adds conditional to properly set `PHP_CS_FIXER_IGNORE_ENV` in windows environments. Before the was being done incorrectly using bash semantics.
=> [make:*] fix bundled php-cs-fixer not working on windows

src/Doctrine/DoctrineHelper.php
Fixes https://github.com/symfony/maker-bundle/issues/1437
This PR removes the use of `Types::ARRAY` and `Types::OBJECT` as they were removed in Doctrine v4.0 (see https://github.com/doctrine/dbal/commit/763b4ad34134bbdb3a8bade640e33f7df2ecfa73).
=> Remove mentions of undefined Doctrine constants Types::ARRAY and Types::OBJECT

.github/workflows/ci-linux.yaml, .github/workflows/ci-windows.yaml, phpunit.xml.dist, src/Test/MakerTestEnvironment.php, tests/Maker/MakeFunctionalTestTest.php, tests/Maker/MakeTestTest.php, tests/RegexTest.php
- tests that use `symfony/panther` are skipped on windows. The windows runner does not chrome/firefox/etc pre-installed.
- fixes regex that gets a list of files create or updated by MakerBundle (used to test those files were actually created). the file path in the output differs on linux, github actions linux images, macos, & windows. The new regex pattern handles all of those cases. This regex is only used in Maker tests
- adds a test for that regex to protect from hidden test failures in the future.
=> [ci] windows tests on GitHub actions

CHANGELOG.md
*February 6th, 2024*
- [#1439](https://github.com/symfony/maker-bundle/pull/1439) - [make:*] improve support for ORM 3.x / DBAL 4.x - *@jrushlow*
- [#1438](https://github.com/symfony/maker-bundle/pull/1438) - Remove mentions of undefined Doctrine constants Types::ARRAY and Types::OBJECT - *@njutn95*
- [#1432](https://github.com/symfony/maker-bundle/pull/1432) - [make:controller] use promoted parameter - *@tacman*
- [#1428](https://github.com/symfony/maker-bundle/pull/1428) - [make:*] use Routing\Attribute\* instead of Routing\Annotation\* - *@jrushlow*
- [#1425](https://github.com/symfony/maker-bundle/pull/1425) - [dx] require >= PHPUnit 9.6, update phpunit schema, deprecate skipOnSymfony7()  - *@jrushlow*
- [#1421](https://github.com/symfony/maker-bundle/pull/1421) - [make:*] drop …
=> [git-released] v1.54.0

src/Maker/MakeCommand.php, src/Resources/config/makers.xml
`PhpCompatUtil` is no longer used in `make:command`
=> [make:command] deprecate passing PhpCompatUtil to the constructor

src/Maker/MakeController.php, src/Resources/config/makers.xml
`PhpCompatUtil` is no longer used in `make:controller`
=> [make:controller] deprecate passing PhpCompatUtil to the constructor

tests/Doctrine/EntityRegeneratorTest.php
```
3x: Not enabling lazy ghost objects is deprecated and will not be supported in Doctrine ORM 3.0. Ensure Doctrine\ORM\Configuration::setLazyGhostObjectEnabled(true) is called to enable them. (ProxyFactory.php:166 called by EntityManager.php:178, https://github.com/doctrine/orm/pull/10837/, package doctrine/orm)
2x in EntityRegeneratorTest::testRegenerateEntities from Symfony\Bundle\MakerBundle\Tests\Doctrine
1x in EntityRegeneratorTest::testXmlRegeneration from Symfony\Bundle\MakerBundle\Tests\Doctrine
```
=> [ci] handle doctrine lazy ghost deprecation in entity regen tests

.github/workflows/ci-linux.yaml
_Waiting on upstream fixes in `symfony/ux-turbo`_
Mercure tests were disabled in https://github.com/symfony/maker-bundle/pull/1439. 
https://github.com/symfony/ux/pull/1471
=> [ci] re-enable mercure tests on linux

src/Maker/MakeEntity.php, tests/Maker/MakeEntityTest.php
Relates to `make:entity` field type question when passing `?` to see all available types.
- dynamically remove types that are unsupported by the platform.
- adds `ascii_string` as an "or" type for `string`
- replacement for #1447 
allows for removed types in DBAL 4 to still be available for users on DBAL 3
fixes #1446
=> [make:entity] only show supported types in cli wizard

src/Test/MakerTestDetails.php, tests/Test/MakerTestDetailsTest.php
`+=` is for arithmetic  and doesn't merge 2 arrays as intended.
https://3v4l.org/FL7cV 
_broke out into separate PR for changelog entry. fixes tests in #1445_
=> [tests] fix broken assignment operator - addExtraDependencies()

src/Maker/MakeEntity.php, src/Resources/config/makers.xml
The `PhpCompatUtil` is no longer used in `make:entity`. As the last parameter of the `final class` constructor - removing it outright will not cause any issues downstream. See https://symfony.com/doc/current/contributing/code/bc.html#note-3
Closes #1374
=> [make:entity] remove PhpCompatUtil constructor argument

src/Generator.php, tests/GeneratorTest.php
Generator was changing namespace of the class with Prefixed namespace, even in the case it was absolute.
Now if class exists, even if it is not starting with backslash `\`, it would be accepted.
https://github.com/symfony/maker-bundle/issues/1371
=> Generator verifies if class exists before altering class name

src/Security/UserClassBuilder.php, tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithPassword.php, tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithoutPassword.php, tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserModelWithPassword.php, tests/Security/fixtures/expected/UserModelWithoutPassword.php
Fixes phpstan warnings on the files generated by make:user
https://github.com/symfony/maker-bundle/issues/1404
=> [make:user] Add phpdocs in class generated by make:user for PHPStan

src/FileManager.php, src/Maker/MakeSerializerNormalizer.php, src/Resources/config/makers.xml, src/Resources/skeleton/serializer/Normalizer.tpl.php
Related to https://github.com/symfony/maker-bundle/issues/1252
This PR aims to do not rely anymore on constructor argument injection and use `NormalizerAwareInterface`/`NormalizerAwareTrait` instead.
Moreover, this allows to not inject explicitly the `ObjectNormalizer` anymore which can be considered as a bad practice as it is a concrete implementation of the `NormalizerInterface`.
=> [make:serializer:normalizer] Inject a NormalizerInterface instead of an ObjectNormalizer

CHANGELOG.md
*February 21st, 2024*
- [#1458](https://github.com/symfony/maker-bundle/pull/1458) - [make:entity] fix require mercure before asking to broadcast entity updates - *@jrushlow*
=> [release] v1.55.1

src/Maker/MakeAuthenticator.php, tests/Maker/MakeAuthenticatorTest.php
Fixes #1412 and adds test to prevent regression
=> [make:auth] Fix 'always-remember-me' param always set to true

src/Doctrine/EntityDetails.php
Because there are many date types, I used to the helper to get the mapping and checked for those.
Fixes #1392
=> [make:*] add `single_text` widget for all date types

src/Maker/MakeResetPassword.php, src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
For the password reset process:
=> [make:reset-password] increase password strength & check for comprimised password

src/Security/UserClassBuilder.php, src/Util/ClassSourceManipulator.php, tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithPassword.php, tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithoutPassword.php
As a result of https://github.com/doctrine/dbal/pull/5656, we should stop using the `unique` property of the `ORM\Column` attribute in the `make:user` command and prefer the `ORM\UniqueConstraint`.
This PR should solve this problem 🙂
=> [make:user] handle ORM\Column.unique deprecation - use ORM\UniqueConstrain

src/Maker/MakeTwigComponent.php, tests/Maker/MakeTwigComponentTest.php
- default to `false` when asking "Make this a live component"
fixes #1395
=> [make:twig-component] default to "no" when asking if is live component

src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
I found 3 issues preventing simple CRUD controller tests classes from passing
this changes the TPL template to address these issues
method: `testNew()`
- bad path (sweet food!?) after creating new entity, changed to `$this-path`
- call to `$this->getRepository()` (no such method) instead of `$this->repository`
method: `testRemove()`
- needs to ADD (persist) fixture into DB to then visit show page and delete, change `remove(...)` to `persist(...)`
.. matt ..
=> [make:crud] fixed issues with make CRUD test Controller generation

src/Maker/MakeSerializerNormalizer.php, src/Resources/config/makers.xml, src/Resources/skeleton/serializer/Normalizer.tpl.php, tests/Maker/MakeSerializerNormalizerTest.php, tests/fixtures/make-serializer-normalizer/EntityFixture.php, tests/fixtures/make-serializer-normalizer/EntityFixtureNormalizer.php, tests/fixtures/make-serializer-normalizer/FooBarNormalizer.php
- `CacheableSupportsMethodInterface` is deprecated since Symfony 6.3 https://github.com/symfony/symfony/blob/3e296f1a924af7ceccaac96d1279c583d32c6ff1/src/Symfony/Component/Serializer/Normalizer/CacheableSupportsMethodInterface.php#L23
- fix normalizer property param name - refs #1273 
- removes legacy test dependency related to symfony <5.4 composer conflict
- use `[#Autowire()]` attribute instead of modifying `services.yaml` 
- import entity class instead of using FQCN in template
=> [make:serializer:normalizer] stop using CacheableSupportsMethodInterface

src/FileManager.php, src/Maker/MakeMigration.php, src/Resources/help/MakeMigration.txt, tests/Maker/MakeMigrationTest.php
Hi,
Related to this #1336 I tried to work on this PR.
Now you can run `make:migration --formatted` to get a formatted SQL migration file.
=> [make:migration] Format the generated migration sql by passing `--formatted` to the command

src/Doctrine/DoctrineHelper.php
fixed: #1002
replace: #1021
sample custom type
```php
<?php
declare(strict_types=1);
namespace App\Doctrine\DBAL\Types;
use Cake\Chronos\Chronos;
use DateTimeImmutable;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\ConversionException;
use Doctrine\DBAL\Types\DateTimeImmutableType;
class ChronosDateTimeType extends DateTimeImmutableType
{
final public const CHRONOS_DATETIME = 'chronos_datetime';
/**
* {@inheritDoc}
*/
public function convertToPHPValue($value, AbstractPlatform $platform): ?Chronos
{
if (null === $value) {
return null;
}
$dateTime = parent::convertToPHPValue($value, $platform);
return Chronos::instance($dateTime);
}
/*
* ....
*/
}
```
this change will get `convertToPHPValue` function return type and set it as property type
if no return type defined …
=> [DoctrineHelper] handle property type for custom doctrine type

src/Resources/config/php-cs-fixer.config.php, src/Util/TemplateLinter.php
when generating form with `EntityType`, the indentation of `options_code` looks wrong
below example is `Foo <-- ManyToMany --> Bar`
Before
```php
<?php
class BarType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options): void
{
$builder
->add('name')
->add('Foo', EntityType::class, [
'class' => Foo::class,
'choice_label' => 'id',
'multiple' => true,
])
;
}
// ....
}
```
After 
```php
<?php
class BarType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options): void
{
$builder
->add('name')
->add('Foo', EntityType::class, [
'class' => Foo::class,
'choice_label' => 'id',
'multiple' => true,
])
;
}
// ....
}
```
=> [make:form] fix generated field options_code indentation

CHANGELOG.md
*March 4th, 2024*
- [#1465](https://github.com/symfony/maker-bundle/pull/1465) [make:twig-component] default to "no" when asking if is live component - *@jrushlow*
- [#1463](https://github.com/symfony/maker-bundle/pull/1463) [make:serializer:normalizer] stop using CacheableSupportsMethodInterface - *@jrushlow*
- [#1460](https://github.com/symfony/maker-bundle/pull/1460) [make:user] handle ORM\Column.unique deprecation - use ORM\UniqueConstrain - *@maelanleborgne*
- [#1413](https://github.com/symfony/maker-bundle/pull/1413) [DoctrineHelper] handle property type for custom doctrine type - *@IndraGunawan*
- [#1405](https://github.com/symfony/maker-bundle/pull/1405) [make:reset-password] increase password strength & check for comprimised password - *@Spomky*
- …
=> [release] v1.56.0

src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php, src/Resources/skeleton/crud/controller/Controller.tpl.php, tests/fixtures/make-crud/expected/WithCustomRepository.php
Fixes #1454 
Replace `request->request` by `request->getPayload()`
=> [make:*] use `getPayload()` instead of accessing `request` on Request objects

src/Maker/MakeEntity.php, tests/Maker/MakeEntityTest.php
Fixes #1379 
Entity name cannot longer have accent :)
=> [make:entity] Prevent entity name from having an accent

.gitattributes
Excludes the following from being "installed" by the user in a project
- https://github.com/symfony/maker-bundle/blob/main/phpunit.xml.dist
- https://github.com/symfony/maker-bundle/blob/main/docker-compose.yml
=> do not include dev files in release

src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
=> [make:registration-form] use validateEmailConfirmationFromRequest() when verifying emails

src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
Use `getString` instead of `get` for request.
=> [make:auth] use `getString()` instead of `get()`

src/Doctrine/EntityClassGenerator.php, src/Maker/Common/EntityIdTypeEnum.php, src/Maker/Common/UidTrait.php, src/Maker/MakeEntity.php, src/Maker/MakeResetPassword.php, src/Maker/MakeUser.php, src/Resources/help/_WithUid.txt, src/Resources/skeleton/doctrine/Entity.tpl.php, tests/Maker/MakeEntityTest.php, tests/Maker/MakeResetPasswordTest.php, tests/Maker/MakeUserTest.php, tests/fixtures/make-user/tests/it_generates_entity_with_password_and_ulid.php
- `make:entity`
- `make:reset-password`
- `make:user`
=> [make:*] allow the option to use ULID's for entity id's

src/Maker/MakeEntity.php
Error says `symfony/mercure` but the `class_exist` looks for `Symfony\Bundle\MercureBundle\DependencyInjection\MercureExtension`.
Switch to `symfony/mercure-bundle` instead.
=> [make:entity] Fix exception message if mercure bundle not found with --broadcast

CHANGELOG.md
*March 22nd, 2024*
- [#1488](https://github.com/symfony/maker-bundle/pull/1488) [make:*] allow the option to use ULID's for entity id's - *@jrushlow*
- [#1484](https://github.com/symfony/maker-bundle/pull/1484) [make:auth] use `getString()` instead of `get()` - *@seb-jean*
- [#1477](https://github.com/symfony/maker-bundle/pull/1477) [make:message] Modernize Messenger\Message class, use PHP8 features - *@lyrixx*
- [#1475](https://github.com/symfony/maker-bundle/pull/1475) [make:user] better exception msg for non-attribute mapping entities - *@jrushlow*
- [#1474](https://github.com/symfony/maker-bundle/pull/1474) [make:entity] Prevent entity name from having an accent - *@Fan2Shrek*
- [#1473](https://github.com/symfony/maker-bundle/pull/1473) [make:*] use `getPayload()` instead of accessing …
=> [release] v1.57.0

src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php, src/Util/ClassSourceManipulator.php, tests/Util/ClassSourceManipulatorTest.php, tests/Util/fixtures/add_getter/User_bool_begins_with_has.php, tests/Util/fixtures/add_getter/User_bool_begins_with_is.php, tests/Util/fixtures/add_setter/User_bool_begins_with_is.php
- Refactoring the getter prefixes  for `make:entity`
- Introducing exceptions for boolean fields : not adding the prefix to getter name if field begins with "is" or "has"
Related to #1492
=> [make:entity] managing keyword prefixes (is, has) for boolean properties getters

src/Util/YamlSourceManipulator.php
It's difficult to debug code in YSM. Let's improve that by:
- implementing type declarations for protected/private properties & methods
refs: #1278 & #1476
=> [ysm] improve type declarations

src/Maker/MakeFixtures.php, src/Maker/MakeMigration.php, src/Maker/MakeValidator.php
- `make:fixtures`
- `make:migration`
- `make:validator`
add `@return` to public method docblocks that do not have return types. The @return type declaration will be converted to an actual method return type in v2.
refs #1498
=> [make:*] add docBlock return types for non-internal makers

src/Test/MakerTestEnvironment.php
we don't commit the lockfile, run upgrade not install...
=> fix exception message when twigcs is not installed

src/Maker/MakeRegistrationForm.php
=> [make:registration] add missing property types

src/Maker/MakeEntity.php
stop relying on type casting - just use a string
refs: #1498
=> [make:entity] ask() doesnt accept "int" only "string"

src/Maker/AbstractMaker.php, src/Maker/MakeListener.php, src/Maker/MakeMigration.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeTest.php
Adds DocBlock type hints to:
_`final` non-`@internal` classes shown below_
```diff
+    /** @param array<class-string, string> $dependencies */
protected function addDependencies(array $dependencies, ?string $message = null): string
```
```diff
+   /** @return void */
public function configureDependencies(DependencyBuilder $dependencies)
```
```diff
+    /** @return void */
public function setApplication(Application $application)
...
+    /** @return void|int */
public function generate(InputInterface $input, ConsoleStyle $io, Generator $generator)
```
```diff
+    * @return string[]
*/
public static function getCommandAliases(): iterable
```
refs #1498
=> [make:*] additional type improvements

.github/workflows/ci-linux.yaml, .github/workflows/ci-static-analysis.yaml, .github/workflows/ci-windows.yaml, phpstan.dist.neon, src/Maker/MakeEntity.php, src/Maker/MakeUser.php, tests/Maker/FunctionalTest.php, tests/Maker/MakeEntityTest.php, tests/Maker/MakeFormTest.php, tests/Maker/MakeMessageTest.php, tests/Maker/MakeMessengerMiddlewareTest.php, tests/Maker/MakeSerializerEncoderTest.php, tests/Maker/MakeTwigExtensionTest.php, tests/Maker/MakeUnitTestTest.php, tests/Maker/MakeValidatorTest.php, tests/Maker/MakeVoterTest.php, tools/phpstan/composer.json, tools/phpstan/includes/.gitignore, tools/phpstan/includes/composer.json
- uses PHPStan to help catch bugs
We'll start with the scope below and slowly open it up as the code base is updated to the desired PHPStan level. 
- `src/Maker`
- `tests/Command`
- `tests/Docker`
- `tests/Maker`
--- 
In our root `composer.json`, we don't `require --dev` packages that are not specifically needed for MakerBundle to function. e.g. `api-platform`. But we _do_ still need those packages for phpstan. for now, the `composer.json` in the `includes` dir will satisfy that need and gives MakerBundle dev's the added benefit of code completion in the IDE.
We currently do not require those "maker specific" packages in our root `composer.json` because it would have adverse side effects in some of our tests. I _think_ in MakerBundle 2.x and/or #1466 - we'll change how we manage …
=> [ci] implement phpstan for static analysis of the codebase

CHANGELOG.md
*April 6th, 2024*
- [#1502](https://github.com/symfony/maker-bundle/pull/1502) [make:*] additional type improvements - *@jrushlow*
- [#1499](https://github.com/symfony/maker-bundle/pull/1499) [make:*] add docBlock return types for non-internal makers - *@jrushlow*
- [#1493](https://github.com/symfony/maker-bundle/pull/1493) [make:entity] managing keyword prefixes (is, has) for boolean properties getters - *@ClemRiviere*
- [#1491](https://github.com/symfony/maker-bundle/pull/1491) [make:webhook] Add new command for Symfony's Webhook Component - *@maelanleborgne*
- [#1487](https://github.com/symfony/maker-bundle/pull/1487) [make:schedule] a new command for creating recurring Symfony Schedules - *@jrushlow*
- [#1219](https://github.com/symfony/maker-bundle/pull/1219) [make:entity] Add PHPDoc …
=> [release] v1.58.0

src/Resources/skeleton/webhook/RequestParser.tpl.php, tests/fixtures/make-webhook/RemoteServiceRequestParser.php
Previously, the generated code of `FooRequestParser::doParse` started with `// Implement your own logic to validate and parse the request, and return a RemoteEvent object.`, followed by an empty line, then some code. I think it may be confusing for the developers, some may think the custom logic should live right bellow the comment and that the following code should not be messed with.  
I think that changing this to `// TODO: Adapt or replace the content of this method to fit your need.` might help clear things up.
Additionally I removed an unnecessary check for null  in the generated code + fixed the payload conversion method in the fixture.
=> [make:webhook] Rephrase comments to be more explicit + minor improvement of generated code

src/Maker/MakeEntity.php, src/Str.php, tests/Maker/MakeEntityTest.php, tests/StrTest.php, tests/fixtures/make-entity/entities/attributes/Friend/User-sub-namespace.php
As discussed in #1292 this is how I see the feature, let me know what you think about it.
New output when using classes with same name:
```
$ bin/console m:entity Order
Your entity already exists! So let's add some new fields!
New property name (press <return> to stop adding fields):
> orderLogistic
Field type (enter ? to see all types) [string]:
> relation
What class should this entity be related to?:
> Logistic\Order
What type of relationship is this?
------------ ----------------------------------------------------------------------------
Type         Description
------------ ----------------------------------------------------------------------------
ManyToOne    Each Order relates to (has) one Logistic\Order.
Each Logistic\Order can relate to (can have) many Order objects.
OneToMany …
```
=> [make:entity] helper message with two classes having the same name under different namespaces

src/Maker/Common/InstallDependencyTrait.php
This header was omitted on accident and the trait was meant to be internal.
https://github.com/symfony/maker-bundle/pull/1491/commits/64622cfcfdc6960549d0ce061540d4a2c6269417
=> [common] add missing class header

src/Maker/MakeRegistrationForm.php, tests/Maker/MakeRegistrationFormTest.php
When creating a registration form and using `verify-email-bundle`, we now add the `bool` property type to `User::isVerified`.
The column `type` definition is dropped - it can be inferred from the property type by doctrine.
=> [make:registration] add `bool` type to User::isVerified

src/Maker/MakeRegistrationForm.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
`sendEmailConfirmation()` && `handleEmailConfirmation()` both have the `$user` type as `UserInterface`. This is pointless other than to ensure we get a "user" object. Seeing as we already know the class details of the "user" object, let's use the class short name instead of `UserInterface` when generating `EmailVerifier`. Improves phpstan in userland.
```diff
// in part
- public function sendEmailConfirmation(UserInterface $user)
+ public function sendEmailConfirmation(<?= $user_class_name ?> $userl)  // generated as "User"
```
- adds `(string)` cast to `getId()` calls on the user object. In cases where the users id is an `int`, this will squash any squawks from phpstan about 
```
Parameter #2 $userId of method SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface::generateSignature() …
```
=> [make:registration] use "User" type in `EmailVerifier::class`

src/Maker/MakeResetPassword.php, src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
- use the "User" entity type where possible. Actual type name is derived from the `ClassNameDetails` object
- annotate the "User" type where an interface signature would conflict with using the actual "User" type declaration.
=> [make:reset-password] improve types for static analysis in userland

src/Maker/Common/CanGenerateTestsTrait.php, src/Maker/MakeCrud.php, src/Maker/MakeRegistrationForm.php, src/Maker/MakeResetPassword.php, src/Resources/config/makers.xml, src/Resources/help/_WithTests.txt, src/Resources/skeleton/registration/Test.WithVerify.tpl.php, src/Resources/skeleton/registration/Test.WithoutVerify.tpl.php, src/Resources/skeleton/resetPassword/Test.ResetPasswordController.tpl.php, tests/Maker/MakeRegistrationFormTest.php, tests/Maker/MakeResetPasswordTest.php, tests/fixtures/make-reset-password/src/Controller/FixtureController.php
_This feature is experimental - generated code is likely to change significantly between point releases._
Adds the ability to pass `--with-tests` to `make:registration`, `make:reset-password`, & `make:crud` and maker will generate a new PHPUnit test tailored for the specific functionality of that maker. If `--with-tests` is _not_ passed as an argument, MakerBundle will ask the user `Do you want to generate PHPUnit tests? [Experimental]`. 
This PR introduces a new internal `CanGenerateTestsTrait` that can be added to any Maker command. The method naming is intended to be intuitive - e.g. `configureCommandWithTestsOption()` should be called from `configureCommand()`, `interactSetGenerateTests()` called in `interact()`, & `shouldGenerateTests()` is used in the `generate()` method in a …
=> [make:*] add ability to generate tests

src/Maker/Security/MakeCustomAuthenticator.php, src/Resources/config/makers.xml, src/Resources/help/security/MakeCustom.txt, src/Resources/skeleton/security/custom/Authenticator.tpl.php, tests/Maker/Security/MakeCustomAuthenticatorTest.php, tests/fixtures/security/make-custom-authenticator/expected/FixtureAuthenticator.php
Replaces the existing `make:auth` command that was originally used to implement authentication with "Guard" based authentication. When we created `make:security:form-login` - our aim was to ultimately remove `make:auth`.
- ~deprecates `make:auth` and it's `MakeAuthenticator::class`~ - deprecated in #1523 for better changelog / release visibility
- introduces `make:security:custom`
- the "custom authenticator" generated replicates the example provided in the security docs: https://symfony.com/doc/current/security/custom_authenticator.html
- `make:security:custom` is intended to be no-frills... It will not work out of the box because it's a "custom" authenticator. The custom implementation details should be generated in userland.
=> [make:security:custom] create a custom authenticator

src/Maker/MakeSerializerEncoder.php, src/Resources/skeleton/serializer/Encoder.tpl.php, tests/Maker/MakeSerializerEncoderTest.php
Handles https://github.com/symfony/symfony/pull/47150 which reverted the changes to:
- https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Serializer/Encoder/DecoderInterface.php
- https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Serializer/Encoder/EncoderInterface.php
- Adds legacy testcase for `6.4`, `DecoderInterface::decode()` return type `mixed` is added in Symfony `7.0`
- Removes legacy test dependencies introduced in https://github.com/symfony/maker-bundle/pull/1063
Fixes #1050
=> [make:serializer:encoder] fix interface signature mismatch in template

src/Resources/skeleton/doctrine/Repository.tpl.php, tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php, tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php, tests/fixtures/make-crud/SweetFoodRepository.php
I removed theses from project project, and my IDE (vscode) and PHPStan are okay with that.
It works, because doctrine has already templated the methods
=> [make:entity] Simplify repository PHPDoc removes method annotations

src/Maker/MakeAuthenticator.php, tests/Maker/MakeAuthenticatorTest.php
The `make:auth` command has been superseded by `make:security:form-login` (#1244) and `make:security:custom` (#1522).
Originally written to create login form authentication back in the days of "Guard Authenticators" - this command has reached it's EOL with the existence of the new Symfony Security System that was introduced in Symfony 5.x.
Although the command class itself is `@internal` - we'll:
- deprecate the command in `v1.59.0` maintaining its existing functionality
- remove the existing functionality _after_ the `v1.59.0` release
- remove the command completely sometime after that. 
I think this will give plenty of time to get the docs & book updated and "gently" push users to `make:security:*`
cc @fabpot - Symfony Book
=> [make:auth] deprecate command

CHANGELOG.md
*April 27th, 2024*
- [#1523](https://github.com/symfony/maker-bundle/pull/1523) [make:auth] deprecate command - *@jrushlow*
- [#1522](https://github.com/symfony/maker-bundle/pull/1522) [make:security:custom] create a custom authenticator - *@jrushlow*
- [#1521](https://github.com/symfony/maker-bundle/pull/1521) [make:reset-password] improve types for static analysis in userland - *@jrushlow*
- [#1520](https://github.com/symfony/maker-bundle/pull/1520) [make:entity] Simplify repository PHPDoc removes method annotations - *@lyrixx*
- [#1519](https://github.com/symfony/maker-bundle/pull/1519) [make:registration] use "User" type in `EmailVerifier::class` - *@jrushlow*
- [#1518](https://github.com/symfony/maker-bundle/pull/1518) [make:registration] add `bool` type to User::isVerified - …
=> [release] v1.59.0

CHANGELOG.md
*May 5th, 2024*
- [#1532](https://github.com/symfony/maker-bundle/pull/1532) [make:auth] only fire deprecation when command is called - *@eltharin*
---
fixes #1537
=> [release] v1.59.1

composer.json
- run `composer tools:upgrade` to install / upgrade `php-cs-fixer`, `phpstan`, & `twigcs`
- run `composer tools:upgrade:php-cs-fixer || phpstan || twigcs` to install / upgrade individual tool
- run `composer tools:run` to run all 3 tools against the code base
- run `composer tools:run:php-cs-fixer || phpstan || twigcs` to run an individual tool against the code base
I've started doing this in other projects & it's a nice little bonus the DX when working on the code base... We can always take it out if we run into problems. Feedback welcome!
=> [dx] make it easier to use tooling for devs

src/Test/MakerTestProcess.php
The timeout for a test process can only be a `float` || `null`. Currently, the suggested `MAKER_PROCESS_TIMEOUT` "null" value is cast as a string. This fixes the exception that is ultimately thrown when attempting to set the timeout as `null` via the env.
_This only affects MakerBundle internal development, specifically, step debugging_
=> [debug] null string literal to null for process timeout

src/Maker/MakeEntity.php, src/Util/ClassSource/Model/ClassProperty.php, src/Util/ClassSourceManipulator.php, src/Validator.php, tests/Maker/MakeEntityTest.php, tests/fixtures/make-entity/entities/attributes/Enum/Role-basic.php
Hi 👋 
The purpose of this PR is to add support for enumerations when creating an entity. 
Instead of introducing a new field type, I've opted to add a prompt to supplement a text field with the enumType option.
---
Edit by @jrushlow 
fixes #1440 fixes #1233
=> [make:entity] add enum support

src/Maker/MakeEntity.php, tests/Maker/MakeEntityTest.php
Following the message https://github.com/symfony/maker-bundle/pull/1474#issuecomment-2027716072, I made some modifications
---
edited by @jrushlow 
fixes #1556
=> [make:entity] confirm to allow non-ascii char's in entity names

src/Test/MakerTestEnvironment.php
Ensure's that the `flex_project` and "apps" created when running maker tests do not attempt to sign commits when `git config global gpgsign=true` || `git config global user.signingkey` are set on the host.
=> [tests] dont sign commits in tests

src/Resources/help/MakeController.txt, tests/Maker/MakeControllerTest.php
- updates the help doc (`bin/console make:controller --help`) to reference `symfony/twig-bundle` is needed to generate twig templates for the controller.
fixes #1066
=> [make:controller] add tests to confirm twig templates generated

src/Maker/MakeSchedule.php, src/Resources/skeleton/scheduler/Schedule.tpl.php, tests/Maker/MakeScheduleTest.php, tests/fixtures/make-schedule/expected/DefaultScheduleWithTransportName.php
Hey ! 👋 
I often use the command `make:schedule` and I wanted to add this new feature : Ask for the `name` used in the attribute `#[AsSchedule]`. 
Console : 
Generated class : 
```php
<?php
namespace App\Scheduler;
use Symfony\Component\Scheduler\Attribute\AsSchedule;
use Symfony\Component\Scheduler\RecurringMessage;
use Symfony\Component\Scheduler\Schedule;
use Symfony\Component\Scheduler\ScheduleProviderInterface;
use Symfony\Contracts\Cache\CacheInterface;
#[AsSchedule]
final class MainSchedule implements ScheduleProviderInterface
{
public function __construct(
private CacheInterface $cache,
) {
}
public function getSchedule(): Schedule
{
return (new Schedule())
->add(
// @TODO - Create a Message to schedule
// RecurringMessage::every('1 hour', new App\Message\Message()),
) …
```
=> [make:schedule] Add transport name for attribute

src/Maker/MakeTwigComponent.php, tests/Maker/MakeTwigComponentTest.php
this PR aims to fix generated twig file path if the twig-component created on a subdirectory
```sh
symfony console make:twig-component "Form\Input" --live
created: src/Twig/Components/Form/Input.php
created: templates/components/Input.html.twig
Success!
To render the component, use <twig:Input />.
```
```sh
symfony console make:twig-component "Form\Input" --live
created: src/Twig/Components/Form/Input.php
created: templates/components/Form/Input.html.twig
Success!
To render the component, use <twig:Form:Input />.
```
=> [make:twig-component] Fix generated twig file location

CHANGELOG.md
*June 10th, 2024*
- [#1534](https://github.com/symfony/maker-bundle/pull/1534) [make:entity] add enum support - *@loicsapone*
- [#1543](https://github.com/symfony/maker-bundle/pull/1543) [dx] make it easier to use tooling for devs - *@jrushlow*
- [#1544](https://github.com/symfony/maker-bundle/pull/1544) [make:webhook] phpstan types and single quotes - *@seb-jean*
- [#1546](https://github.com/symfony/maker-bundle/pull/1546) [make:message] phpstan types - *@seb-jean*
- [#1545](https://github.com/symfony/maker-bundle/pull/1545) 1545 [make:crud] use getString() instead of get() for csrf token - *@seb-jean*
- [#1568](https://github.com/symfony/maker-bundle/pull/1568) [make:schedule] Add transport name for attribute - *@NicolasJourdan* 
- …
=> [release] v1.60.0

src/Resources/skeleton/registration/RegistrationController.tpl.php, src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php, tests/fixtures/make-registration-form/expected/RegistrationControllerCustomAuthenticator.php, tests/fixtures/make-registration-form/expected/RegistrationControllerFormLogin.php, tests/fixtures/make-registration-form/expected/RegistrationControllerNoLogin.php
---
edited by: @jrushlow 
Improves type hints in generated code to reduce userland PHPStan squawks.
=> [make:registration-form] improve generated types for phpstan

src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php, tests/Maker/MakeResetPasswordTest.php
---
edited by: @jrushlow 
Improves type hints in generated code to reduce userland PHPStan squawks.
=> [make:reset-password] improve generated typehints for phpstan

src/Security/UserClassBuilder.php, tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserEntityWithPassword.php, tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php, tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php, tests/Security/fixtures/expected/UserModelWithPassword.php
---
Edited by: @jrushlow
Improves types in templates to handle PHPStan squawks in userland code
=> [make:user] fix `getPassword()` return type in certain instance with `PasswordAuthenticatedUserInterface`

src/Maker/MakeTwigComponent.php, src/Resources/config/makers.xml, tests/Maker/MakeTwigComponentTest.php, tests/fixtures/make-twig-component/custom_twig_component.yaml
Small change in the way `make:twig-component` works when determining the namespace of the class to create.
In before, the namespace was hard coded. This is still good, but in cases where your Twig Component class namespace may have changed (i.e. your website is divided into `src/Admin` and `src/Site` and you've modified your `twig_component.yaml` so that your TwigComponents live under `src/Site/Twig/Components`), the component class would be still created under `src/Twig/Components`.
I've improved the command to read this config and automatically create the component under the first entry in this file. If no config is found, then we can use the old default.
TODOS:
=> [make:twig-component] Improve `make:twig-component` by reading the configuration file

src/Util/TemplateLinter.php, tests/Util/TemplateLinterTest.php
See https://github.com/symfony/maker-bundle/pull/1429/files#r1653262959.
---
Edited by @jrushlow
Uses the `PHP_WINDOWS_VERSION_MAJOR` constant to determine if the OS is Windows based. Rather than doing a string `win` comparison with `\PHP_OS`. The `PHP_WINDOWS_VERSION_*` constants are only available in the Windows environment. https://www.php.net/manual/en/info.constants.php#constant.php-windows-version-major
Linter tests are still skipped on windows based CI.
=> [ci] allow template linter tests on OSX (Darwin)

src/DependencyInjection/Configuration.php, src/DependencyInjection/MakerExtension.php, src/Generator.php, src/Maker/MakeCrud.php, src/Maker/MakeVoter.php, src/Resources/config/services.xml, src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php, src/Resources/skeleton/security/Voter.tpl.php, src/Util/ClassSource/Model/ClassData.php, src/Util/TemplateComponentGenerator.php, tests/Doctrine/EntityRegeneratorTest.php, tests/Maker/MakeVoterTest.php, tests/Util/ClassSource/ClassDataTest.php, tests/Util/TemplateComponentGeneratorTest.php, tests/fixtures/make-crud/expected/WithCustomRepository.php, tests/fixtures/make-voter/expected/FooBarVoter.php, tests/fixtures/make-voter/expected/not_final_FooBarVoter.php
- introduces 2 new configuration values:
- `generate_final_classes`: Defaults to `true` - When true, all non-entity classes generated by MakerBundle will be final.
- `generate_final_entities`: Defaults to `false` - When true, all entity classes generated by MakerBundle will be final.
- introduces an internal `ClassData` object that represents all of the meta data needed to generate a class from a template. It combines parts of `ClassNameDetails` & `UseStatementGenerator, while adding logic to generate a class declaration conditionally including the `final` keyword & `extends` class.
- `ClassData` is configured by `TemplateComponentGenerator` to handle `root_namespace`, `generate_final_classes`, & `generate_final_entities` if passed as a template `class_data` variable to …
=> [make:crud|voter] generate classes with final keyword

src/Resources/skeleton/crud/controller/Controller.tpl.php, src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php, src/Util/TemplateComponentGenerator.php, tests/fixtures/make-crud/expected/WithCustomRepository.php, tests/fixtures/make-crud/tests/it_generates_basic_crud.php, tests/fixtures/make-crud/tests/it_generates_crud_with_custom_controller.php, tests/fixtures/make-crud/tests/it_generates_crud_with_custom_root_namespace.php
I propose to remove the `/` from the index action URL because all other URLs in the [src/Resources/skeleton/crud/controller/Controller.tpl.php](https://github.com/seb-jean/maker-bundle/blob/main/src/Resources/skeleton/crud/controller/Controller.tpl.php) file do not end with a `/`. This is more consistent.
=> [make:crud] Remove `/` from from index action URL

CHANGELOG.md
*August 29th, 2024*
- [#1583](https://github.com/symfony/maker-bundle/pull/1583) [make:crud] Remove / from from index action URL - *@seb-jean*
- [#1579](https://github.com/symfony/maker-bundle/pull/1579) [make:listener] Match event name against active events class/id - *@maelanleborgne*
- [#1571](https://github.com/symfony/maker-bundle/pull/1571) [make:twig-component] Improve `make:twig-component` by reading the configuration file - *@shadowc*
- [#1549](https://github.com/symfony/maker-bundle/pull/1549) [make:registration-form] improve generated types for phpstan - *@seb-jean*
- [#1548](https://github.com/symfony/maker-bundle/pull/1548) [make:reset-password] improve generated typehints for phpstan - *@seb-jean*
- [#1539](https://github.com/symfony/maker-bundle/pull/1539) [make:crud|voter] …
=> [release] v1.61.0

src/Resources/skeleton/validator/Constraint.tpl.php
- drops the previously generated annotations in the constraint
- sync generated constraint with symfony docs
=> [make:validator] drop annotation support in constraint

src/Generator.php, src/Maker/MakeValidator.php, src/Maker/MakeVoter.php, src/Resources/skeleton/validator/Constraint.tpl.php, tests/Maker/MakeValidatorTest.php, tests/fixtures/make-validator/expected/FooBar.php, tests/fixtures/make-validator/expected/FooBarValidator.php
generates `final` classes for the generated validator and constraint based on MakerBundle's config preferences
- adds generated file comparison to test suite
- adds a new internal generator method to create classes from `ClassData` objects - this will replace the existing `generateClass()` method in the future.
- adds test fixture to compare generated code to our template
=> [make:validator] generate final classes

tests/Maker/MakeEntityTest.php
Unable to run `make:entity` tests that require `api-platform` as a dependency. API Platform `v3.4` does not allow for `api_platform.keep_legacy_inflector` to be set, but it's automatically included in `<3.4` recipe(s). No recipe exists yet for `>=3.4`.
Skipped Test Cases:
- `it_creates_a_new_class_and_api_resource`
- `it_makes_new_entity_no_to_all_extras`
Tests to be re-enabled once https://github.com/symfony/recipes/pull/1339 is merged.
---
There are more complex ways to restrict these 2 test cases to run on `=<3.3` - but this is the easiest path forward at the moment.
=> [ci] temp. skip API Platform tests - recipe conflict

src/Generator.php, src/Maker/MakeController.php, src/Resources/skeleton/controller/Controller.tpl.php, src/Util/ClassSource/Model/ClassData.php, tests/Maker/MakeControllerTest.php, tests/Util/ClassSource/ClassDataTest.php, tests/fixtures/make-controller/expected/FinalController.php, tests/fixtures/make-controller/expected/FinalControllerWithTemplate.php, tests/fixtures/make-controller/tests/it_generates_a_controller.php, tests/fixtures/make-controller/tests/it_generates_a_controller_with_twig.php, tests/fixtures/make-controller/tests/it_generates_an_invokable_controller.php
Adds the ability to generate controllers with the `final` PHP class keyword based on MakerBundle's config preferences.
- enhances the `ClassData` object to handle instantiation with absolute class name values. E.g. `\Foo\Bar\Controller` and in turn, calling `getNamespace()` will not include the `root_namespace` e.g. `Foo\Bar`
- adds test assertions to compare the generated controller to a known test fixture (expected controller)
- `Generator`'s `createClassFromClassData()` is able to generate regular classes and controller classes based on the `$isController` method argument. This will eventually replace the existing `Generator::createClass()` && `Generator::createController()` methods.
=> [make:controller] generate final controller class

src/Maker/MakeController.php, src/Resources/skeleton/controller/test/Test.tpl.php, tests/Maker/MakeControllerTest.php
_This feature is experimental - generated code is likely to change significantly between point releases._
Adds the ability to pass `--with-tests` to `make:controller` and maker will generate a new PHPUnit test tailored for the specific functionality of that maker. If `--with-tests` is _not_ passed as an argument, MakerBundle will ask the user `Do you want to generate PHPUnit tests? [Experimental]`.
=> [make:controller] add ability to create controller with tests

src/Maker/MakeController.php
- use class properties instead of abusing console argument/option system
- separate interaction & generation logic into their appropriate class methods
=> [make:controller] maker housekeeping

src/Test/MakerTestRunner.php
When we run tests from the `./tests/tmp/cache` directory, the built PHPUnit path contains 2 slashes because the [`MakerTestRunner::getPath()`](https://github.com/symfony/maker-bundle/blob/main/src/Test/MakerTestRunner.php#L81) method already prefix with a slash.
```
⬇️
./tests/tmp/cache/maker_app_7e4ffd082daa1224b6cfdeae54f3e3b2_current//bin/phpunit
```
Remove the prefixed slash in `bin/phpunit`
=> [tests] Fix double slashes in tmp PHPUnit path

src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
Use lowercase-first version of entity to name repository variable in the test class
e.g. if entity named “Product” then test class repository variable will be “productRepository” rather than just “repository”
this makes copy-paste of setup code from other test classes simpler, when a related entity needs to be created for test cases
=> [make:crud] name repository variable with entity prefix when generating tests

docs/index.rst
Someone on Stack Overflow asked (question is not published yet) if `make:entity` can be used without Doctrine.
It looks like MakerBundle can only manage Doctrine entities, so I added it in the docs, hopefully that is true. Otherwise we'll have to change or close this PR.
=> [doc] make:entity requires Doctrine

src/Util/ClassSourceManipulator.php
Hi there, pretty strange edge case found in #1612 when `mixed` type is detected from a custom doctrine type and was set to be nullable. Maker tried to set is as `?mixed` which is not allowed.
That should fix this behavior.
closes #1612
=> [make:entity] Issue with detected mixed type set to be nullable

src/Util/ClassSourceManipulator.php, templates/verifyEmail/EmailVerifier.tpl.php, tests/Util/fixtures/add_setter/User_bool_begins_with_is.php
When generating a new entity, if we name a boolean property with the prefix "is", this prefix is removed to construct the setter.
example:
```
bool $isInternational;
public function isInternational(): ?bool
{
return $this->isInternational;
}
public function setInternational(bool $isInternational): static
{
$this->isInternational = $isInternational;
return $this;
}
```
This is breaking when we want to access the property via a form :
> [NoSuchPropertyException]
> HTTP 500 Internal Server Error
> The method "isInternational" in class "App\Entity\Conference" requires 0 arguments, but should accept only 1.. Make the property public, add a setter, or set the "mapped" field option in the form type to be false.
This PR revert this change introduce in [PR …
=> [make-entity]Keep the 'is' prefixes for booleans properties setters

src/Generator.php
Removes the prepended '\\' in the Exceptionmessage when encountering an invalid FCQN 
#1615 
#SymfonyHackday
=> [doc]remove prepended doubleslash in exceptionmessage

config/help/MakeStimulusController.txt, src/Maker/MakeStimulusController.php, templates/stimulus/Controller.tpl.php, tests/Maker/MakeStimulusControllerTest.php, tests/fixtures/make-stimulus-controller/with_classes.js, tests/fixtures/make-stimulus-controller/with_targets.js, tests/fixtures/make-stimulus-controller/with_targets_values_classes.js, tests/fixtures/make-stimulus-controller/with_values.js, tests/fixtures/make-stimulus-controller/without_targets.js
Hello,
this PR adds new features to the Stimulus controller maker (and updates minor things)
Also
Most of things here are based on feedback received or mistakes seen frequently... but everything is _of course_ very open to debate and suggestions 🤗 
I tried to make a clean commit history to ease review, but if you do want, i can split this PR.
PS: I intentionally did _not_ add outlets to this maker. They are a very advanced feature that can often lead to debatable choices in terms of component architecture, isolation, and more.
=> [make:stimulus-controller] Add `classes` support, generate usage code, fix doc, add tests

src/Maker/MakeTwigComponent.php
alternative of #1618
changes from https://github.com/symfony/maker-bundle/pull/1571 break if config is in php files even $namespace has a default value
=> [make:twig-component] do not throw an error if config file does not exist
