src/Command/AbstractCommand.php
src/DependencyBuilder.php
src/FileManager.php
src/Generator.php
src/Resources/skeleton/form/Type.php.txt
src/Str.php
tests/Command/FunctionalTest.php
tests/StrTest.php

Spotted with PHP-CS-Fixer and Php Inspections (EA Extended).

Minor code improvements

---

src/Command/AbstractCommand.php
src/Command/MakeSubscriberCommand.php
src/Validator.php

Add NotBlank constraint to interactive arguments

---

src/Command/MakerCommand.php

Add a missing import after the revamp of the Command class by @weaverryan

Add missing import

---

composer.json

Reported here: https://twitter.com/electricmaxxx/status/935944477998534658

Remove minimum-stability from Composer config

---

src/Maker/MakeEntity.php
src/Maker/MakeMigration.php
src/Maker/MakeSerializerEncoder.php
src/Maker/MakeSubscriber.php
src/Maker/MakeValidator.php
src/Maker/MakeVoter.php

Remove extra dots

---

.appveyor/composer.bat
.travis.yml
appveyor.yml
src/Maker/MakeController.php
src/Resources/skeleton/controller/twig_template.tpl.php
src/Test/MakerTestCase.php
src/Test/MakerTestDetails.php
src/Test/MakerTestEnvironment.php
src/Test/MakerTestProcess.php
tests/Maker/FunctionalTest.php
tests/Util/AutoloaderUtilTest.php

Test PR to see if tests work as expected

[WIP - Experimental] Superfast tests

---

src/GeneratorTwigHelper.php
src/Resources/skeleton/controller/twig_template.tpl.php

Wow, creating a controller, going to its URL, and opening it in one click!

Add source links to generated twig template

---

src/Resources/doc/index.rst

Fix small typo

---

src/FileManager.php
src/Test/MakerTestEnvironment.php
tests/FileManagerTest.php

Thanks to @yann-eugone for helping to spot & debug this!

Fixing a bug where having relativizePath failed if root was /src

---

src/Maker/MakeEntity.php
src/Util/ClassSourceManipulator.php

Remove support for the deprecated json_array Doctrine type

---

src/Doctrine/EntityRegenerator.php

updating latest cs

---

src/Util/AutoloaderUtil.php
tests/Util/AutoloaderUtilTest.php

Fixes conflict between namespace psr-4 prefix and target directory structure

---

src/Resources/skeleton/security/UserProvider.tpl.php

Typo found by someone in my training :) @joboscribe

Had stateless backwards

---

src/Doctrine/DoctrineHelper.php

Class not found on make:entity --regenerate

---

src/Maker/MakeSerializerNormalizer.php
src/Resources/config/makers.xml
src/Resources/help/MakeSerializerNormalizer.txt
src/Resources/skeleton/serializer/Normalizer.tpl.php

[Serializer] Add a 'make:serializer:normalizer' command

---

src/Resources/skeleton/form/Type.tpl.php
src/Resources/skeleton/registration/RegistrationController.tpl.php

Fixes #339 and https://github.com/symfony/maker-bundle/pull/333#issuecomment-449399522

Fixing phpcs and making the registration controller more explicit

---

src/FileManager.php
src/Generator.php
src/GeneratorTwigHelper.php
src/Maker/MakeController.php
src/Resources/skeleton/controller/twig_template.tpl.php

Fixed the IDE link in new controller + make code simpler in the generated controller

---

src/Resources/skeleton/crud/controller/Controller.tpl.php

Better CS in make:crud command

---

src/DependencyInjection/Configuration.php
src/Generator.php
src/Maker/MakeMigration.php
src/Test/MakerTestProcess.php
src/Util/AutoloaderUtil.php
tests/Doctrine/EntityRegeneratorTest.php
tests/Maker/FunctionalTest.php

updating test system to work with latest vendors

Update tests and make:migration fix

---

.travis.yml

Add PHP 7.3 to Travis

---

src/Maker/MakeFunctionalTest.php
tests/Maker/FunctionalTest.php

Fixes one little detail from #381

Fixing bad check for trait

---

.travis.yml

I realized that we're not testing against low deps. I've taken most of this from WebpackEncoreBundle.
Cheers!

Travis: testing high and low deps

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/security_password_hashtag.test

Escape hashtag in yaml

---

src/Resources/skeleton/crud/controller/Controller.tpl.php

Remove useless parameter in the edit redirect like as suggested here : https://github.com/symfony/maker-bundle/issues/257#issuecomment-475234045.

[CRUD] Fix redirect to index after edit

---

src/Generator.php
src/Resources/skeleton/serializer/Normalizer.tpl.php

related to https://github.com/symfony/maker-bundle/pull/371
Added the condition to check if the CacheableSupportsMethodInterface exists.

[Serializer] Normalizer now implements CacheableSupportsMethodInterface with condition

---

src/Maker/MakeRegistrationForm.php

The bug caused an error from the choice question

Fxix make:registration-form bug when asking to authenticate but no authenticators

---

src/Maker/MakeUser.php

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Fixed tickets | #435   
| License       | MIT

[make:user] Respect custom root namespace

---

src/Maker/MakeMigration.php

Take care of migrations argument

---

src/Resources/skeleton/doctrine/Repository.tpl.php

Application of https://github.com/symfony/symfony/pull/32817

[Doctrine][Repository] deprecated replacement

---

src/Util/ComposerAutoloaderFinder.php

`$autoloader` can be a Closure

Prevent autoload closure

---

src/Maker/MakeFunctionalTest.php
src/Resources/skeleton/test/Functional.tpl.php
tests/Maker/FunctionalTest.php

Hope this will be useful for others.
Let me know if there are some mistakes to fix !

[make:functional-test] Use Panther when available.

---

.travis.yml
appveyor.yml
phpunit.xml.dist
src/Doctrine/EntityClassGenerator.php
src/Doctrine/EntityRegenerator.php
src/Maker/MakeUser.php
src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
src/Resources/skeleton/doctrine/Repository.tpl.php
src/Resources/skeleton/security/UserProvider.tpl.php
src/Test/MakerTestCase.php

Fixes https://github.com/symfony/maker-bundle/issues/382
Needs https://github.com/symfony/symfony/pull/31153

Allow rehashing passwords when possible and needed

---

src/Util/YamlSourceManipulator.php

remove useless comment

---

src/Maker/MakeMigration.php

Hi,
A very small fix noticed when playing a little with the `make:migration` command :)

Make Migration - Fix db/shard options value forward

---

src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php

To eliminate long debug time and bug fixing in case of change login route.  Connected with https://github.com/symfony/symfony-docs/pull/13363

Move login route to const

---

src/Resources/skeleton/registration/twig_template.tpl.php

Add submit button type

---

src/Maker/MakeResetPassword.php

updated success message for `make:reset-password`

add suggestion to create a reset password link

---

src/Maker/MakeMigration.php

Fix in #596 looks wrong to me as we are looking for the Doctrine Migration bundle here.

Fix class name

---

.php_cs.dist
appveyor.yml
composer.json
src/DependencyBuilder.php
src/Maker/MakeEntity.php
src/Maker/MakeUser.php
src/Test/MakerTestCase.php
src/Util/MakerFileLinkFormatter.php
tests/FileManagerTest.php
tests/Maker/MakeEntityTest.php
tests/Maker/MakeFunctionalTestTest.php
tests/Maker/MakeMessageTest.php
tests/Maker/MakeUserTest.php
tests/Util/MakerFileLinkFormatterTest.php

officially requiring php 7.1

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/simple_hash_add_indexed_item.test

Fixing a YamlSourceManipulator bug when adding an indexed array to a hash

---

tests/Maker/FunctionalTest.php

forgot the forgotten password smoke test

remove forgotten password reference in smoke test

---

src/Maker/MakeResetPassword.php

Make reset-password warn when symfony/mailer missing

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/add_item_and_sort.test
tests/Util/yaml_fixtures/simple_sequence_change_item.test

Add Failing Test

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/keyed_array_item.test

Not sure about test case naming, tell me if you have a better one :)
Part of #608
```
In YamlSourceManipulator.php line 549:
Cannot find the key "Bearer"  
```

Add test case for keyed array item

---

src/Maker/MakeAuthenticator.php

Hi, catch a little miss arg for updater in ```maker:auth```.

Fix logout setup on updater

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/add_key_to_2nd_level_hash.test

Fix adding a key to a second-level hash after a key with empty value in YAML

---

src/Util/YamlSourceManipulator.php
tests/Util/yaml_fixtures/add_indented_array.test

Fix adding an item to an array with known indentation in YAML

---

.github/workflows/ci.yml
.travis.yml

Enhancement: Run PHP-CS-Fixer & composer validate via GithubActions instead of Travis

---

.github/workflows/ci.yml

Fix: Checkout for "Coding Standards"-build

---

.travis.yml

Fix: Travis build

---

src/Str.php
tests/StrTest.php

and added test cases.
Or would you expect sth else from this method? 🤔

Fix: asHumanWords()

---

src/Test/MakerTestEnvironment.php

It has more todo with `skeleton` instead of `flex`

Enhancement: Rename variable

---

src/Test/MakerTestCase.php

Enhancement: Support Composer 2

---

src/Test/MakerTestEnvironment.php

Fix: symfony/skeleton dev branch

---

tests/Maker/MakeRegistrationFormTest.php

[Test] Adding missing profiler that's needed in Symfony 5.2

---

.gitattributes

These files are not necessary in a released version

Enhancement: Add more files to .gitattributes file

---

src/Test/MakerTestDetails.php

update test details for new flex recipes 

---

src/Docker/DockerDatabaseServices.php

fixed typo in postgres extension name

---

src/Test/MakerTestCase.php

This will allow to create a custom kernel to register your own bundles and configuration.

Create MakerTestCase::createKernel method

---

src/Console/MigrationDiffFilteredOutput.php
src/FileManager.php
src/Maker/MakeEntity.php
src/Maker/MakeUser.php
src/Test/MakerTestEnvironment.php
src/Util/PhpCompatUtil.php
src/Util/YamlSourceManipulator.php
src/Validator.php
tests/Util/PhpVersionTest.php

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5426 updated the Symfony ruleset which broke CI. Changes included in this PR are as a result of `php-cs-fixer fix`

[CI] fix php-cs-fixer squawks in CI

---

src/Maker/MakeUser.php
src/Resources/config/makers.xml

PR #590 added `DoctrineHelper` to `MakeResetPassword` but the service is never used.

[Internal] [User] removed unused service from make:user

---

src/Maker/MakeResetPassword.php

We're currently abusing input arguments by using them as data stores internally. This PR is the first of many to refactor makers to replace input argument with proper class properties, add method return types where possible, and general housekeeping to improve code readability. 
The first maker to use this approach was `make:docker:database` found [here](https://github.com/symfony/maker-bundle/blob/main/src/Maker/MakeDockerDatabase.php).
One decision we should make now before proceeding with refactoring additional makers is in regards to the docBlock format we should use for properties. Symfony uses the expanded format - but this can lead to reduced readability with a class that has multiple properties. As a solution to this we could break tradition and use single line docBlocks strictly …

[DX] [ResetPassword] lets stop abusing input arguments

---

src/Maker/MakeCrud.php
tests/Maker/MakeCrudTest.php
tests/fixtures/MakeCrudCustomController/src/Entity/SweetFood.php
tests/fixtures/MakeCrudCustomController/tests/GeneratedCrudControllerTest.php

Hi! 
This adds a 2nd question to `make:crud`:
Very simple - I have hit a few cases where I wanted this :).
Cheers!

allowing the user to choose a controller class for make:crud

---

src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php

Fix #845
Can happen when [`DoctrineOrmMappingsPass::createAnnotationMappingDriver()`](https://github.com/doctrine/DoctrineBundle/blob/155a870ecbd035963e6b450e0f235e69c48cab30/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php#L124) is used in a third-party bundle.

Fix dealing with Definition objects in SetDoctrineAnnotatedPrefixesPass

---

tests/Doctrine/EntityRegeneratorTest.php

silence deprecation's triggered in `EntityRegenerator` tests for the newly added `override_url` feature in DoctrineBundle 2.3

[tests][doctrine] handle deprecated override_url

---

src/Maker/MakeRegistrationForm.php
src/Resources/skeleton/authenticator/login_form.tpl.php
src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
src/Resources/skeleton/resetPassword/ResetPasswordRequestFormType.tpl.php

#823 
[Here](https://github.com/symfony/maker-bundle/blob/29774a9c6a4a9d37137ad704859be640d04b9dc2/src/Maker/MakeRegistrationForm.php#L438), how can I determine if it's an email or a username ?

Add autocomplete html tag to forms

---

.gitignore
.php-cs-fixer.dist.php
composer.json
src/Resources/test/.php_cs.test

[ci] upgrade php-cs-fixer 2.x -> 3.0

---

src/Resources/doc/index.rst

To keep composer convention
`composer require --dev XXXX`

Update code example

---

src/Maker/MakeResetPassword.php
tests/Maker/MakeResetPasswordTest.php

Add all missed dependencies to make:reset-password

---

src/DependencyInjection/CompilerPass/SetDoctrineAnnotatedPrefixesPass.php

Fix method call definition

---

src/EventRegistry.php

can be verified here:
https://github.com/symfony/security-core/blob/5.4/AuthenticationEvents.php
https://github.com/symfony/security-core/blob/6.0/AuthenticationEvents.php

Fix FQCN of 'security.authentication.success' event

---

src/Resources/skeleton/security/Voter.tpl.php

This fixes #1051 
this refactoring improves the code and makes it more maintainable in the future after the class has been generated by the command `make:voter`.

[Voter] Refactor attributes

---

src/Resources/skeleton/resetPassword/twig_request.tpl.php

Hi,
I changed the case to be like the standard coding:
https://twig.symfony.com/doc/3.x/coding_standards.html

[reset-password] Coding standards - Twig

---

src/Resources/skeleton/twig/Extension.tpl.php

Update the version version in the help link

[make:twig-extension] reference twig 3.x docs in generated extension

---

src/Util/ClassSourceManipulator.php
tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php
tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/User.php
tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php
tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php
tests/Doctrine/fixtures/expected_xml/src/Entity/UserXml.php
tests/Util/fixtures/add_many_to_many_relation/User_simple_inverse.php
tests/Util/fixtures/add_many_to_many_relation/User_simple_no_inverse.php
tests/Util/fixtures/add_many_to_many_relation/User_simple_owning.php
tests/Util/fixtures/add_one_to_many_relation/User_simple.php
tests/Util/fixtures/add_one_to_many_relation/User_simple_orphan_removal.php
tests/Util/fixtures/add_one_to_many_relation/User_with_use_statements.php

use method add() instead of [] in collection adder-method

use method add() instead of [] in collection adder-method

---

appveyor.yml

appveyor runner no longer include sqlite by default

[ci] install sqlite3 in appveyor tests

---

src/Maker/MakeResetPassword.php
src/Test/MakerTestKernel.php
src/Test/MakerTestRunner.php
src/Util/ComposeFileManipulator.php

- php-cs-fixer it up
- fix `framework/http_method_override` in tests
- use new flex dsn for persistence

[ci] several fixes

---

src/Doctrine/DoctrineHelper.php

Update doctrinehelper to work with symfony 4.4

fix attribute support in symfony 4.4 applications

---

src/Resources/skeleton/serializer/Normalizer.tpl.php

[make:serializer] use empty string in str_replace

---

.github/workflows/ci.yaml
src/Test/MakerTestRunner.php

- handle pgsql v15 recipe change in persistence DSN - `.env`
- test against PHP 8.2 in tests
- add symfony 6.3 in tests

[tests] handle postgres v15

---

tests/fixtures/make-twig-component/tests/it_generates_live_component.php

[make:twig-component] handle upstream changes to how live components are rendered

---

composer.json

Ref https://getcomposer.org/doc/04-schema.md#keywords

Add composer `dev` keyword

---

src/Maker/MakeAuthenticator.php
src/Resources/skeleton/authenticator/login_form.tpl.php

Tweaks to rememberme feature

---

src/Maker/MakeFixtures.php

UseStatement is not used as it should

Fix UseStatementGenerator usage in MakeFixtures.php

---

src/Maker/MakeDockerDatabase.php
src/Resources/help/MakeDockerDatabase.txt
src/Util/ComposeFileManipulator.php
tests/Maker/MakeDockerDatabaseTest.php
tests/Util/ComposeFileManipulatorTest.php

Change docker-compose.yaml to compose.yaml

New Name of Docker compose file

---

src/Test/MakerTestRunner.php

See - https://github.com/symfony/recipes/pull/1284

[ci] handle postgres 16 recipe support in .env

---

src/Maker/MakeAuthenticator.php
src/Maker/MakeController.php
src/Maker/MakeCrud.php
src/Maker/MakeRegistrationForm.php
src/Maker/MakeResetPassword.php
src/Maker/Security/MakeFormLogin.php
src/Security/SecurityControllerBuilder.php
tests/Security/fixtures/expected/SecurityController_login.php
tests/Security/fixtures/expected/SecurityController_login_logout.php
tests/Security/fixtures/expected/SecurityController_logout.php
tests/Util/ClassSourceManipulatorTest.php
tests/Util/UseStatementGeneratorTest.php
tests/Util/fixtures/add_method/Controller_with_action.php
tests/fixtures/make-crud/expected/WithCustomRepository.php
tests/fixtures/make-registration-form/standard_setup/src/Controller/TestingController.php
tests/fixtures/security/make-form-login/expected/LoginController.php
tests/fixtures/security/make-form-login/expected/SecurityController.php
tests/fixtures/security/make-form-login/expected/SecurityControllerWithoutLogout.php

[make:*] use Routing\Attribute\* instead of Routing\Annotation\*

---

.php-cs-fixer.dist.php
src/Command/MakerCommand.php
src/Doctrine/DoctrineHelper.php
src/Generator.php
src/InputAwareMakerInterface.php
src/Maker/AbstractMaker.php
src/Maker/MakeAuthenticator.php
src/Maker/MakeEntity.php
src/Maker/MakeTest.php
src/Maker/MakeUser.php
src/Renderer/FormTypeRenderer.php
src/Security/InteractiveSecurityHelper.php
src/Security/UserClassBuilder.php
src/Util/YamlSourceManipulator.php
src/Validator.php
tests/Util/AutoloaderUtilTest.php
tests/Util/ClassSourceManipulatorTest.php

- apply `nullable_type_declaration_for_default_null_value` php-cs-fixer rule
- minor cleanup

[ci] php-cs-fixer fix && review

---

.gitattributes

don't install development files when adding maker-bundle to a project

---

src/Maker/MakeEntity.php
tests/Maker/MakeEntityTest.php

[make:entity] fix require mercure before asking to broadcast entity updates

---

src/Maker/MakeMigration.php

[make:migration] add ability to specify a configuration file

---

src/Doctrine/DoctrineHelper.php

[make:user] better exception msg for non-attribute mapping entities

---

src/Maker/MakeEntity.php

Fixed a tiny typo in make:entity

[make:entity] Fix a small typo in a make:entity error message

---

tests/RegexTest.php

[ci] minor refactor to allow for more regex tests

---

src/Maker/MakeStimulusController.php

-  [x] decide if an empty array is even needed
refs: #1498

[make:stimulus-controller] use named arguments where possible

---

src/Maker/MakeStimulusController.php

[make:stimulus-controller] more typehints

---

src/Maker/MakeAuthenticator.php

[make:authenticator] more typehints / types

---

src/Maker/Security/MakeFormLogin.php
src/Resources/skeleton/security/formLogin/Test.LoginController.tpl.php
tests/Maker/Security/MakeFormLoginTest.php
tests/fixtures/security/make-form-login/FixtureController.php

[make:security:form-login] add ability to generate tests

---

src/Maker/MakeTwigComponent.php

[make:twig-component] Fix config file in error messages

---

src/Maker/MakeTwigComponent.php

Custom root namespace make:twig-component
